
    const Marks = [
       {
        "Sr. no": 1,
        "STUDENT NAME": "ADITY",
        "FATHER'S NAME": "CHDAMME LAL",
        "MOTHER'S NAME": "SUMAN DEVI",
        "Add": "THEEPURI",
        "mob. no": 9917851229,
        "cast": "KUSHWAH",
        "Column8": "OBC"
       },
       {
        "Sr. no": 2,
        "STUDENT NAME": "AMIT",
        "FATHER'S NAME": "JASWANT SINGH",
        "MOTHER'S NAME": "SHRIMATI DEVI",
        "Add": "NEEVARI",
        "mob. no": 8126341225,
        "cast": "KUSHWAH",
        "Column8": "OBC"
       },
       {
        "Sr. no": 3,
        "STUDENT NAME": "GAURUI",
        "FATHER'S NAME": "PRADEEP",
        "MOTHER'S NAME": "SHASHI",
        "Add": "DHIMISHRI",
        "mob. no": 6397413298,
        "cast": "KUSHWAH",
        "Column8": "OBC",
        "Column9": "7\/10\/2010"
       },
       {
        "Sr. no": 4,
        "STUDENT NAME": "JITENDRA ",
        "FATHER'S NAME": "KESHAV SINGH",
        "MOTHER'S NAME": "GUDIYA DEVI",
        "Add": "NEEVARI",
        "mob. no": 8279819513,
        "cast": "KUSHWAH",
        "Column8": "OBC",
        "Column9": "1\/1\/2011"
       },
       {
        "Sr. no": 5,
        "STUDENT NAME": "KAJAL",
        "FATHER'S NAME": "MAHENDRA SINGH",
        "MOTHER'S NAME": "SAVITA DEVI",
        "Add": "NAGLA MUKTA",
        "mob. no": 9012751319,
        "cast": "SAXENA",
        "Column8": "OBC"
       },
       {
        "Sr. no": 6,
        "STUDENT NAME": "KHUSHI ",
        "FATHER'S NAME": "MUNNA LAL",
        "MOTHER'S NAME": "CHHOTI DEVI",
        "Add": "THEEPURI",
        "mob. no": 9917827918,
        "cast": "KUSHWAH",
        "Column8": "OBC"
       },
       {
        "Sr. no": 7,
        "STUDENT NAME": "LOVE KUSH",
        "FATHER'S NAME": "GYANI RAM",
        "MOTHER'S NAME": "MANJU DEVI",
        "Add": "PURA RAMPA ",
        "mob. no": 9258521191,
        "cast": "KUSHWAH",
        "Column8": "OBC",
        "Column9": "8\/22\/2008"
       },
       {
        "Sr. no": 8,
        "STUDENT NAME": "MANISH",
        "FATHER'S NAME": "JAWAHAR SINGH",
        "MOTHER'S NAME": "RACHANA DEVI",
        "Add": " GADHI PARSHURAM",
        "mob. no": 9717617314,
        "cast": "DIWAKAR",
        "Column8": "SC",
        "Column9": "7\/23\/2009"
       },
       {
        "Sr. no": 9,
        "STUDENT NAME": "MUSKAN",
        "FATHER'S NAME": "SUBHASH CHAND",
        "MOTHER'S NAME": "SUNEETA DEVI",
        "Add": "PURA DURJI",
        "mob. no": 9536470109,
        "cast": "KUSHWAH",
        "Column8": "OBC"
       },
       {
        "Sr. no": 10,
        "STUDENT NAME": "NANDANI ",
        "FATHER'S NAME": "SATENDRA SINGH",
        "MOTHER'S NAME": "SARVESH DEVI",
        "Add": "THEEPURI",
        "mob. no": 9759111057,
        "cast": "KUSHWAH",
        "Column8": "OBC"
       },
       {
        "Sr. no": 11,
        "STUDENT NAME": "NARGESH",
        "FATHER'S NAME": "RAFEEK KHAN ABBASH",
        "MOTHER'S NAME": "PARVEEN",
        "Add": "KANHA PURA",
        "mob. no": 7037336283,
        "cast": "ABBAS",
        "Column8": "OBC"
       },
       {
        "Sr. no": 12,
        "STUDENT NAME": "PAYAL",
        "FATHER'S NAME": "BRIJ KISHOR",
        "MOTHER'S NAME": "MEERA DEVI",
        "Add": "PURA DURJI",
        "mob. no": 9871880156,
        "cast": "KUSHWAH",
        "Column8": "OBC"
       },
       {
        "Sr. no": 13,
        "STUDENT NAME": "PAYAL",
        "FATHER'S NAME": "HARENDRA SINGH",
        "MOTHER'S NAME": "SEEMA DEVI",
        "Add": "NAGLA MUKTA",
        "mob. no": 9758063838,
        "cast": "RATHOR",
        "Column8": "OBC"
       },
       {
        "Sr. no": 14,
        "STUDENT NAME": "PRABHAT SHEKHAWAT",
        "FATHER'S NAME": "MANOJ SINGH SHEKHAWAT",
        "MOTHER'S NAME": "MEERA DEVI",
        "Add": "PENTI KHERA",
        "mob. no": 7505179190,
        "cast": "RAJ POOT",
        "Column8": "OBC"
       },
       {
        "Sr. no": 15,
        "STUDENT NAME": "PRAVESH",
        "FATHER'S NAME": "SORAN SINGH",
        "MOTHER'S NAME": "GUDDI DEVI",
        "Add": "NEEVARI",
        "mob. no": 8936987621,
        "cast": "KUSHWAH",
        "Column8": "OBC"
       },
       {
        "Sr. no": 16,
        "STUDENT NAME": "PRINCE KUSHWAH",
        "FATHER'S NAME": "KESHAV SINGH",
        "MOTHER'S NAME": "MEENU DEVI",
        "Add": "NEEVARI",
        "mob. no": 7500432316,
        "cast": "KUSHWAH",
        "Column8": "OBC",
        "Column9": "1\/1\/2010"
       },
       {
        "Sr. no": 17,
        "STUDENT NAME": "PRIYANKA",
        "FATHER'S NAME": "RAM BABU",
        "MOTHER'S NAME": "RAJ KUMARI",
        "Add": "PURA DURJI",
        "mob. no": 9917848690,
        "cast": "KUSHWAH",
        "Column8": "OBC"
       },
       {
        "Sr. no": 18,
        "STUDENT NAME": "SANTOSH",
        "FATHER'S NAME": "SHRI BHAGWAN",
        "MOTHER'S NAME": "NEELAVATI DEVI",
        "Add": "PURA DURJI",
        "mob. no": 9719044699,
        "cast": "KUSHWAH",
        "Column8": "OBC"
       },
       {
        "Sr. no": 19,
        "STUDENT NAME": "SAURABH ",
        "FATHER'S NAME": "RAKESH SINGH",
        "MOTHER'S NAME": "MEENA DEVI",
        "Add": "PURA DURJI",
        "mob. no": 8006639477,
        "cast": "KUSHWAH",
        "Column8": "OBC"
       },
       {
        "Sr. no": 20,
        "STUDENT NAME": "SHIVAM PRAKASH",
        "FATHER'S NAME": "RAM PRAKASH",
        "MOTHER'S NAME": "MAMTA DEVI",
        "Add": "PURA DURJI",
        "mob. no": 9870604446,
        "cast": "KUSHWAH",
        "Column8": "OBC",
        "Column9": "6\/21\/2011"
       },
       {
        "Sr. no": 21,
        "STUDENT NAME": "SHIVAM",
        "FATHER'S NAME": "RAMHET SINGH",
        "MOTHER'S NAME": "MEENA DEVI",
        "Add": "PURA DURJI",
        "mob. no": 9548231486,
        "cast": "KUSHWAH",
        "Column8": "OBC",
        "Column9": "1\/1\/2011"
       },
       {
        "Sr. no": 22,
        "STUDENT NAME": "SHIVAM",
        "FATHER'S NAME": "MURARI LAL",
        "MOTHER'S NAME": "RAJ KUMARI",
        "Add": "PURA RAMPA ",
        "mob. no": 8077518936,
        "cast": "KUSHWAH",
        "Column8": "OBC"
       },
       {
        "Sr. no": 23,
        "STUDENT NAME": "SHIVAM RAGHUVANSHI",
        "FATHER'S NAME": "SULTAN SINGH",
        "MOTHER'S NAME": "RAM VATI DEVI",
        "Add": "NAGLA MUKTA",
        "mob. no": 9719959934,
        "cast": "RAGHUVANSHI",
        "Column8": "GENERAL",
        "Column9": "9\/8\/2010"
       },
       {
        "Sr. no": 24,
        "STUDENT NAME": "SHIVAM",
        "FATHER'S NAME": "MAHAVEER SINGH",
        "MOTHER'S NAME": "SARADHA DEVI",
        "Add": "NAGLA MUKTA",
        "mob. no": 7535054604,
        "cast": "KUSHWAH",
        "Column8": "OBC"
       },
       {
        "Sr. no": 25,
        "STUDENT NAME": "SHIVANI",
        "FATHER'S NAME": "KALI CHARAN",
        "MOTHER'S NAME": "MEENA DEVI",
        "Add": "PURA DURJI",
        "mob. no": 9761529697,
        "cast": "KUSHWAH",
        "Column8": "OBC"
       },
       {
        "Sr. no": 26,
        "STUDENT NAME": "SHIVANI",
        "FATHER'S NAME": "SULTAN SINGH",
        "MOTHER'S NAME": "RAM VATI DEVI",
        "Add": "NAGLA MUKTA",
        "mob. no": 979959934,
        "cast": "RAGHUVANSHI",
        "Column8": "GEN"
       },
       {
        "Sr. no": 27,
        "STUDENT NAME": "SHLOK SHEKHAWAT",
        "FATHER'S NAME": "MANOJ SINGH SHEKHAWAT",
        "MOTHER'S NAME": "MEERA DEVI",
        "Add": "PAINTI KHERA",
        "mob. no": 7505179190,
        "cast": "RAJ POOT",
        "Column8": "OBC"
       },
       {
        "Sr. no": 28,
        "STUDENT NAME": "SHYAM SUNDER ",
        "FATHER'S NAME": "SHYAM BABU"
       },
       {
        "Sr. no": 29,
        "STUDENT NAME": "SONAM KUSHWAH",
        "FATHER'S NAME": "MUNNA LAL KUSHWAH",
        "MOTHER'S NAME": "JAVITA DEVI",
        "Add": "MAHARAM PURA",
        "mob. no": 9309708049,
        "cast": "KUSHWAH",
        "Column8": "OBC"
       },
       {
        "Sr. no": 30,
        "STUDENT NAME": "VEERENDRA",
        "FATHER'S NAME": "PATIRAM",
        "MOTHER'S NAME": "REKHA DEVI",
        "Add": "NEEVARI",
        "mob. no": 8869840644,
        "cast": "KUSHWAH",
        "Column8": "OBC"
       },
       {
        "Sr. no": 1,
        "STUDENT NAME": "ADITY",
        "HINDI": 18,
        "ENGLISH": 7,
        "MATHS": 7,
        "COMPUTER": 18,
        "DRAWING": 40,
        "G . K": 7,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 147,
        "%": 32.67,
        "Column15": 16,
        "Column16": 17,
        "Column17": 18,
        "Column18": 19,
        "Column19": 20,
        "Column20": 21,
        "Column21": 22,
        "Column22": 23,
        "Column23": 24,
        "Column24": 25,
        "Column25": 26,
        "Column26": 27,
        "Column27": 28,
        "Column28": 29,
        "Column29": 30,
        "Column30": 31
       },
       {
        "Sr. no": 2,
        "STUDENT NAME": "AMIT",
        "HINDI": 26,
        "ENGLISH": 34,
        "MATHS": 18,
        "COMPUTER": 44,
        "DRAWING": 47,
        "G . K": 30,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 249,
        "%": 55.33,
        "Column15": "P",
        "Column16": "P",
        "Column17": "P",
        "Column18": "P",
        "Column19": "P",
        "Column20": "P",
        "Column21": "P",
        "Column22": "P",
        "Column23": "P",
        "Column24": "P",
        "Column25": "P",
        "Column26": "P",
        "Column27": "P",
        "Column28": "P",
        "Column29": "P",
        "Column30": "P"
       },
       {
        "Sr. no": 3,
        "STUDENT NAME": "GAURUI",
        "HINDI": 24,
        "ENGLISH": 28,
        "MATHS": 38,
        "COMPUTER": 33,
        "DRAWING": 45,
        "G . K": 31,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 249,
        "%": 55.33
       },
       {
        "Sr. no": 4,
        "STUDENT NAME": "JITENDRA ",
        "HINDI": 34,
        "ENGLISH": 21,
        "MATHS": 48,
        "COMPUTER": 46,
        "DRAWING": 33,
        "G . K": 27,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 259,
        "%": 57.56
       },
       {
        "Sr. no": 5,
        "STUDENT NAME": "KAJAL",
        "HINDI": 34,
        "ENGLISH": 40,
        "MATHS": 38,
        "COMPUTER": 35,
        "DRAWING": 44,
        "G . K": 26,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 267,
        "%": 59.33
       },
       {
        "Sr. no": 6,
        "STUDENT NAME": "KHUSHI ",
        "HINDI": 37,
        "ENGLISH": 39,
        "MATHS": 40,
        "COMPUTER": 32,
        "DRAWING": 42,
        "G . K": 25,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 265,
        "%": 58.89
       },
       {
        "Sr. no": 7,
        "STUDENT NAME": "LOVE KUSH",
        "HINDI": 20,
        "ENGLISH": 10,
        "MATHS": 45,
        "COMPUTER": 45,
        "DRAWING": 40,
        "G . K": 19,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 229,
        "%": 50.89
       },
       {
        "Sr. no": 8,
        "STUDENT NAME": "MANISH",
        "HINDI": 30,
        "ENGLISH": 19,
        "MATHS": 32,
        "COMPUTER": 41,
        "DRAWING": 40,
        "G . K": 23,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 235,
        "%": 52.22
       },
       {
        "Sr. no": 9,
        "STUDENT NAME": "MUSKAN",
        "HINDI": 21,
        "ENGLISH": 22,
        "MATHS": 17,
        "COMPUTER": 14,
        "DRAWING": 35,
        "G . K": 17,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 176,
        "%": 39.11
       },
       {
        "Sr. no": 10,
        "STUDENT NAME": "NANDANI ",
        "HINDI": 31,
        "ENGLISH": 28,
        "MATHS": 27,
        "COMPUTER": 32,
        "DRAWING": 44,
        "G . K": 31,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 243,
        "%": 54
       },
       {
        "Sr. no": 11,
        "STUDENT NAME": "NARGESH",
        "HINDI": 20,
        "ENGLISH": 18,
        "MATHS": 22,
        "COMPUTER": 23,
        "DRAWING": 45,
        "G . K": 12,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 190,
        "%": 42.22
       },
       {
        "Sr. no": 12,
        "STUDENT NAME": "PAYAL",
        "HINDI": 29,
        "ENGLISH": 33,
        "MATHS": 41,
        "COMPUTER": 31,
        "DRAWING": 40,
        "G . K": 31,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 255,
        "%": 56.67
       },
       {
        "Sr. no": 13,
        "STUDENT NAME": "PAYAL",
        "HINDI": 26,
        "ENGLISH": 30,
        "MATHS": 29,
        "COMPUTER": 38,
        "DRAWING": 43,
        "G . K": 28,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 244,
        "%": 54.22
       },
       {
        "Sr. no": 14,
        "STUDENT NAME": "PRABHAT SHEKHAWAT",
        "HINDI": 38,
        "ENGLISH": 45,
        "MATHS": 34,
        "COMPUTER": 46,
        "DRAWING": 48,
        "G . K": 49,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 310,
        "%": 68.89
       },
       {
        "Sr. no": 15,
        "STUDENT NAME": "PRAVESH",
        "HINDI": 5,
        "ENGLISH": 3,
        "MATHS": 0,
        "COMPUTER": 6,
        "DRAWING": 38,
        "G . K": 5,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 107,
        "%": 23.78
       },
       {
        "Sr. no": 16,
        "STUDENT NAME": "PRINCE KUSHWAH",
        "HINDI": 15,
        "ENGLISH": 12,
        "MATHS": 31,
        "COMPUTER": 42,
        "DRAWING": 37,
        "G . K": 9,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 196,
        "%": 43.56
       },
       {
        "Sr. no": 17,
        "STUDENT NAME": "PRIYANKA",
        "HINDI": 20,
        "ENGLISH": 23,
        "MATHS": 11,
        "COMPUTER": 23,
        "DRAWING": 38,
        "G . K": 17,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 182,
        "%": 40.44
       },
       {
        "Sr. no": 18,
        "STUDENT NAME": "SANTOSH",
        "HINDI": 10,
        "ENGLISH": 20,
        "MATHS": 16,
        "COMPUTER": 18,
        "DRAWING": 42,
        "G . K": 12,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 168,
        "%": 37.33
       },
       {
        "Sr. no": 19,
        "STUDENT NAME": "SAURABH ",
        "HINDI": 27,
        "ENGLISH": 4,
        "MATHS": 34,
        "COMPUTER": 37,
        "DRAWING": 37,
        "G . K": 15,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 204,
        "%": 45.33
       },
       {
        "Sr. no": 20,
        "STUDENT NAME": "SHIVAM PRAKASH",
        "HINDI": 33,
        "ENGLISH": 15,
        "MATHS": 40,
        "COMPUTER": 45,
        "DRAWING": 43,
        "G . K": 21,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 247,
        "%": 54.89
       },
       {
        "Sr. no": 21,
        "STUDENT NAME": "SHIVAM",
        "HINDI": 19,
        "ENGLISH": 14,
        "MATHS": 30,
        "COMPUTER": 26,
        "DRAWING": 42,
        "G . K": 17,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 198,
        "%": 44
       },
       {
        "Sr. no": 22,
        "STUDENT NAME": "SHIVAM",
        "HINDI": 21,
        "ENGLISH": 18,
        "MATHS": 37,
        "COMPUTER": 34,
        "DRAWING": 35,
        "G . K": 20,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 215,
        "%": 47.78
       },
       {
        "Sr. no": 23,
        "STUDENT NAME": "SHIVAM RAGHUVANSHI",
        "HINDI": 11,
        "ENGLISH": 6,
        "MATHS": 15,
        "COMPUTER": 15,
        "DRAWING": 35,
        "G . K": 11,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 143,
        "%": 31.78
       },
       {
        "Sr. no": 24,
        "STUDENT NAME": "SHIVAM",
        "HINDI": 5,
        "ENGLISH": 2,
        "MATHS": 17,
        "COMPUTER": 30,
        "DRAWING": 38,
        "G . K": 7,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 149,
        "%": 33.11
       },
       {
        "Sr. no": 25,
        "STUDENT NAME": "SHIVANI",
        "HINDI": 29,
        "ENGLISH": 11,
        "MATHS": 4,
        "COMPUTER": 25,
        "DRAWING": 49,
        "G . K": 23,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 191,
        "%": 42.44
       },
       {
        "Sr. no": 26,
        "STUDENT NAME": "SHIVANI",
        "ENGLISH": 37,
        "MATHS": 21,
        "DRAWING": 42,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 150,
        "%": 33.33
       },
       {
        "Sr. no": 27,
        "STUDENT NAME": "SHLOK SHEKHAWAT",
        "HINDI": 45,
        "ENGLISH": 42,
        "MATHS": 46,
        "COMPUTER": 46,
        "DRAWING": 49,
        "G . K": 49,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 327,
        "%": 72.67
       },
       {
        "Sr. no": 28,
        "STUDENT NAME": "SHYAM SUNDER ",
        "HINDI": 17,
        "ENGLISH": 20,
        "MATHS": 17,
        "COMPUTER": 35,
        "DRAWING": 37,
        "G . K": 18,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 194,
        "%": 43.11
       },
       {
        "Sr. no": 29,
        "STUDENT NAME": "SONAM KUSHWAH",
        "HINDI": 15,
        "ENGLISH": 5,
        "MATHS": 6,
        "COMPUTER": 27,
        "DRAWING": 39,
        "G . K": 16,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 158,
        "%": 35.11
       },
       {
        "Sr. no": 30,
        "STUDENT NAME": "VEERENDRA",
        "HINDI": 31,
        "ENGLISH": 15,
        "MATHS": 28,
        "COMPUTER": 28,
        "DRAWING": 41,
        "G . K": 30,
        "PHYSICAL EDUCATION": 50,
        "TOTAL": 223,
        "%": 49.56
       },
       {
        "id": "20220701",
        "Session": 2022,
        "RollNo": "01",
        "STUDENT": "ADITY",
        "FATHER": "CHDAMME LAL",
        "Class": "07",
        "HINDI": 33,
        "ENGLISH": 10,
        "MATHS": 32,
        "SCINCE": 17,
        "Sst": 0,
        "COMPUTER": 33,
        "DRAWING": 35,
        "GK": 33,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 243,
        "PRECENTAGE": 54
       },
       {
        "id": "20220702",
        "RollNo": "02",
        "STUDENT": "AMIT",
        "FATHER": "JASWANT SINGH",
        "Class": "07",
        "HINDI": 44,
        "ENGLISH": 47,
        "MATHS": 45,
        "SCINCE": 40,
        "Sst": 9,
        "COMPUTER": 35,
        "DRAWING": 40,
        "GK": 45,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 355,
        "PRECENTAGE": 78.88888888888889
       },
       {
        "id": "20220703",
        "RollNo": "03",
        "STUDENT": "GAURUI",
        "FATHER": "PRADEEP",
        "Class": "07",
        "HINDI": 40,
        "ENGLISH": 33,
        "MATHS": 45,
        "SCINCE": 31,
        "Sst": 12,
        "COMPUTER": 16,
        "DRAWING": 35,
        "GK": 45,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 307,
        "PRECENTAGE": 68.22222222222221
       },
       {
        "id": "20220704",
        "RollNo": "04",
        "STUDENT": "JITENDRA ",
        "FATHER": "KESHAV SINGH",
        "Class": "07",
        "HINDI": 44,
        "ENGLISH": 49,
        "MATHS": 50,
        "SCINCE": 44,
        "Sst": 38,
        "COMPUTER": 40,
        "DRAWING": 35,
        "GK": 45,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 395,
        "PRECENTAGE": 87.77777777777777
       },
       {
        "id": "20220705",
        "RollNo": "05",
        "STUDENT": "KAJAL",
        "FATHER": "MAHENDRA SINGH",
        "Class": "07",
        "HINDI": 45,
        "ENGLISH": 45,
        "MATHS": 42,
        "SCINCE": 40,
        "Sst": 18,
        "COMPUTER": 32,
        "DRAWING": 43,
        "GK": 45,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 360,
        "PRECENTAGE": 80
       },
       {
        "id": "20220706",
        "RollNo": "06",
        "STUDENT": "KHUSHI ",
        "FATHER": "MUNNA LAL",
        "Class": "07",
        "HINDI": 40,
        "ENGLISH": 23,
        "MATHS": 48,
        "SCINCE": 16,
        "Sst": 16,
        "COMPUTER": 32,
        "DRAWING": 47,
        "GK": 45,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 317,
        "PRECENTAGE": 70.44444444444444
       },
       {
        "id": "20220707",
        "RollNo": "07",
        "STUDENT": "LOVE KUSH",
        "FATHER": "GYANI RAM",
        "Class": "07",
        "HINDI": 43,
        "ENGLISH": 31,
        "MATHS": 45,
        "SCINCE": 30,
        "Sst": 5,
        "COMPUTER": 20,
        "DRAWING": 34,
        "GK": 40,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 298,
        "PRECENTAGE": 66.22222222222223
       },
       {
        "id": "20220708",
        "RollNo": "08",
        "STUDENT": "MANISH",
        "FATHER": "JAWAHAR SINGH",
        "Class": "07",
        "HINDI": 44,
        "ENGLISH": 41,
        "MATHS": 50,
        "SCINCE": 43,
        "Sst": 20,
        "COMPUTER": 15,
        "DRAWING": 33,
        "GK": 45,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 341,
        "PRECENTAGE": 75.77777777777777
       },
       {
        "id": "20220709",
        "RollNo": "09",
        "STUDENT": "MUSKAN",
        "FATHER": "SUBHASH CHAND",
        "Class": "07",
        "HINDI": "A",
        "ENGLISH": 23,
        "MATHS": 42,
        "SCINCE": 21,
        "Sst": 13,
        "COMPUTER": 22,
        "DRAWING": 30,
        "GK": 15,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 216,
        "PRECENTAGE": 48
       },
       {
        "id": "20220710",
        "RollNo": "10",
        "STUDENT": "NANDANI ",
        "FATHER": "SATENDRA SINGH",
        "Class": "07",
        "HINDI": 38,
        "ENGLISH": 18,
        "MATHS": 44,
        "SCINCE": 29,
        "Sst": 10,
        "COMPUTER": 12,
        "DRAWING": 46,
        "GK": 45,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 292,
        "PRECENTAGE": 64.88888888888889
       },
       {
        "id": "20220711",
        "RollNo": "11",
        "STUDENT": "NARGESH",
        "FATHER": "RAFEEK KHAN ABBASH",
        "Class": "07",
        "HINDI": 24,
        "ENGLISH": 19,
        "MATHS": 27,
        "SCINCE": 16,
        "Sst": 15,
        "COMPUTER": 14,
        "DRAWING": 30,
        "GK": 45,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 240,
        "PRECENTAGE": 53.333333333333336
       },
       {
        "id": "20220712",
        "RollNo": "12",
        "STUDENT": "PAYAL",
        "FATHER": "BRIJ KISHOR",
        "Class": "07",
        "HINDI": 38,
        "ENGLISH": 26,
        "MATHS": 49,
        "SCINCE": 13,
        "Sst": 10,
        "COMPUTER": 30,
        "DRAWING": 43,
        "GK": 45,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 304,
        "PRECENTAGE": 67.55555555555556
       },
       {
        "id": "20220713",
        "RollNo": "13",
        "STUDENT": "PAYAL",
        "FATHER": "HARENDRA SINGH",
        "Class": "07",
        "HINDI": 45,
        "ENGLISH": 41,
        "MATHS": 45,
        "SCINCE": 45,
        "Sst": 18,
        "COMPUTER": 38,
        "DRAWING": 45,
        "GK": 45,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 372,
        "PRECENTAGE": 82.66666666666667
       },
       {
        "id": "20220714",
        "RollNo": "14",
        "STUDENT": "PRABHAT SHEKHAWAT",
        "FATHER": "MANOJ SINGH SHEKHAWAT",
        "Class": "07",
        "HINDI": 44,
        "ENGLISH": 45,
        "MATHS": 49,
        "SCINCE": 38,
        "Sst": 25,
        "COMPUTER": 41,
        "DRAWING": 43,
        "GK": 48,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 383,
        "PRECENTAGE": 85.11111111111111
       },
       {
        "id": "20220715",
        "RollNo": "15",
        "STUDENT": "PRAVESH",
        "FATHER": "SORAN SINGH",
        "Class": "07",
        "HINDI": 14,
        "ENGLISH": 9,
        "MATHS": 14,
        "SCINCE": 4,
        "Sst": 7,
        "COMPUTER": 12,
        "DRAWING": 40,
        "GK": 20,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 170,
        "PRECENTAGE": 37.77777777777778
       },
       {
        "id": "20220716",
        "RollNo": "16",
        "STUDENT": "PRINCE KUSHWAH",
        "FATHER": "KESHAV SINGH",
        "Class": "07",
        "HINDI": 28,
        "ENGLISH": 12,
        "MATHS": 42,
        "SCINCE": 4,
        "Sst": 4,
        "COMPUTER": 22,
        "DRAWING": 31,
        "GK": 40,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 233,
        "PRECENTAGE": 51.77777777777778
       },
       {
        "id": "20220717",
        "RollNo": "17",
        "STUDENT": "PRIYANKA",
        "FATHER": "RAM BABU",
        "Class": "07",
        "HINDI": 34,
        "ENGLISH": 23,
        "MATHS": 39,
        "SCINCE": 15,
        "Sst": 7,
        "COMPUTER": "A",
        "DRAWING": 45,
        "GK": 15,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 228,
        "PRECENTAGE": 50.66666666666667
       },
       {
        "id": "20220718",
        "RollNo": "18",
        "STUDENT": "SANTOSH",
        "FATHER": "SHRI BHAGWAN",
        "Class": "07",
        "HINDI": 24,
        "ENGLISH": 20,
        "MATHS": 35,
        "SCINCE": 10,
        "Sst": 17,
        "COMPUTER": 27,
        "DRAWING": 40,
        "GK": 15,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 238,
        "PRECENTAGE": 52.888888888888886
       },
       {
        "id": "20220719",
        "RollNo": "19",
        "STUDENT": "SAURABH ",
        "FATHER": "RAKESH SINGH",
        "Class": "07",
        "HINDI": 36,
        "ENGLISH": 20,
        "MATHS": 28,
        "SCINCE": 11,
        "Sst": 3,
        "COMPUTER": 24,
        "DRAWING": 38,
        "GK": 40,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 250,
        "PRECENTAGE": 55.55555555555556
       },
       {
        "id": "20220720",
        "RollNo": "20",
        "STUDENT": "SHIVAM PRAKASH",
        "FATHER": "RAM PRAKASH",
        "Class": "07",
        "HINDI": 43,
        "ENGLISH": 36,
        "MATHS": 45,
        "SCINCE": 31,
        "Sst": 14,
        "COMPUTER": 38,
        "DRAWING": 35,
        "GK": 45,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 337,
        "PRECENTAGE": 74.8888888888889
       },
       {
        "id": "20220721",
        "RollNo": "21",
        "STUDENT": "SHIVAM",
        "FATHER": "RAMHET SINGH",
        "Class": "07",
        "HINDI": 24,
        "ENGLISH": 12,
        "MATHS": 48,
        "SCINCE": 12,
        "Sst": 7,
        "COMPUTER": 28,
        "DRAWING": 38,
        "GK": 15,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 234,
        "PRECENTAGE": 52
       },
       {
        "id": "20220722",
        "RollNo": "22",
        "STUDENT": "SHIVAM",
        "FATHER": "MURARI LAL",
        "Class": "07",
        "HINDI": 43,
        "ENGLISH": 20,
        "MATHS": 45,
        "SCINCE": 17,
        "Sst": 9,
        "COMPUTER": 19,
        "DRAWING": 40,
        "GK": 45,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 288,
        "PRECENTAGE": 64
       },
       {
        "id": "20220723",
        "RollNo": "23",
        "STUDENT": "SHIVAM RAGHUVANSHI",
        "FATHER": "SULTAN SINGH",
        "Class": "07",
        "HINDI": 43,
        "ENGLISH": 12,
        "MATHS": "A",
        "SCINCE": 17,
        "Sst": 22,
        "COMPUTER": 19,
        "DRAWING": 30,
        "GK": 30,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 223,
        "PRECENTAGE": 49.55555555555556
       },
       {
        "id": "20220724",
        "RollNo": "24",
        "STUDENT": "SHIVAM",
        "FATHER": "MAHAVEER SINGH",
        "Class": "07",
        "HINDI": 30,
        "ENGLISH": 13,
        "MATHS": 31,
        "SCINCE": 18,
        "Sst": 10,
        "COMPUTER": 23,
        "DRAWING": 41,
        "GK": 45,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 261,
        "PRECENTAGE": 57.99999999999999
       },
       {
        "id": "20220725",
        "RollNo": "25",
        "STUDENT": "SHIVANI",
        "FATHER": "KALI CHARAN",
        "Class": "07",
        "HINDI": 28,
        "ENGLISH": 7,
        "MATHS": 37,
        "SCINCE": "A",
        "Sst": 0,
        "COMPUTER": 21,
        "DRAWING": 34,
        "GK": 25,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 202,
        "PRECENTAGE": 44.888888888888886
       },
       {
        "id": "20220726",
        "RollNo": "26",
        "STUDENT": "SHIVANI",
        "FATHER": "SULTAN SINGH",
        "Class": "07",
        "HINDI": 43,
        "ENGLISH": 17,
        "MATHS": "A",
        "SCINCE": 24,
        "Sst": "A",
        "COMPUTER": 23,
        "DRAWING": 36,
        "GK": 45,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 238,
        "PRECENTAGE": 52.888888888888886
       },
       {
        "id": "20220727",
        "RollNo": "27",
        "STUDENT": "SHLOK SHEKHAWAT",
        "FATHER": "MANOJ SINGH SHEKHAWAT",
        "Class": "07",
        "HINDI": 45,
        "ENGLISH": 43,
        "MATHS": 27,
        "SCINCE": 44,
        "Sst": 20,
        "COMPUTER": 42,
        "DRAWING": 45,
        "GK": 45,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 361,
        "PRECENTAGE": 80.22222222222221
       },
       {
        "id": "20220728",
        "RollNo": "28",
        "STUDENT": "SHYAM SUNDER ",
        "FATHER": "SHYAM BABU",
        "Class": "07",
        "HINDI": 30,
        "MATHS": 50,
        "SCINCE": 4,
        "Sst": 14,
        "COMPUTER": 32,
        "DRAWING": 29,
        "GK": 22,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 231,
        "PRECENTAGE": 51.33333333333333
       },
       {
        "id": "20220729",
        "RollNo": "29",
        "STUDENT": "SONAM KUSHWAH",
        "FATHER": "MUNNA LAL KUSHWAH",
        "Class": "07",
        "HINDI": 29,
        "ENGLISH": 18,
        "MATHS": 37,
        "SCINCE": 22,
        "Sst": 7,
        "COMPUTER": 20,
        "DRAWING": 42,
        "GK": 38,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 263,
        "PRECENTAGE": 58.44444444444444
       },
       {
        "id": "20220730",
        "RollNo": "30",
        "STUDENT": "VEERENDRA",
        "FATHER": "PATIRAM",
        "Class": "07",
        "HINDI": 45,
        "ENGLISH": 40,
        "MATHS": 50,
        "SCINCE": 36,
        "Sst": 16,
        "COMPUTER": 39,
        "DRAWING": 45,
        "GK": 23,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 344,
        "PRECENTAGE": 76.44444444444444
       },
       {
        "id": "2022"
       },
       {
        "id": "20220801",
        "RollNo": "01",
        "STUDENT": "ANJALI",
        "FATHER": "RAJENDRA",
        "Class": "08",
        "HINDI": 44,
        "ENGLISH": 31,
        "MATHS": 39,
        "SCINCE": 45,
        "Sst": 49,
        "COMPUTER": 50,
        "DRAWING": 45,
        "GK": 50,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 403,
        "PRECENTAGE": 89.55555555555556
       },
       {
        "id": "20220802",
        "RollNo": "02",
        "STUDENT": "ROPAM ",
        "FATHER": "JASWANT SINGH",
        "Class": "08",
        "HINDI": 48,
        "ENGLISH": 34,
        "MATHS": 23,
        "SCINCE": 42,
        "Sst": 40,
        "COMPUTER": 50,
        "DRAWING": 47,
        "GK": 50,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 384,
        "PRECENTAGE": 85.33333333333334
       },
       {
        "id": "20220803",
        "RollNo": "03",
        "STUDENT": "BHARATI",
        "FATHER": "PAPPU SINGH",
        "Class": "08",
        "HINDI": 39,
        "ENGLISH": 28,
        "MATHS": 22,
        "SCINCE": 20,
        "Sst": 47,
        "COMPUTER": 50,
        "DRAWING": 42,
        "GK": 50,
        "PHYSICALEDUCATION": 48,
        "TOTAL": 346,
        "PRECENTAGE": 76.88888888888889
       },
       {
        "id": "20220804",
        "RollNo": "04",
        "STUDENT": "MANU",
        "FATHER": "JAY PAL",
        "Class": "08",
        "HINDI": 23,
        "ENGLISH": 12,
        "MATHS": 14,
        "SCINCE": 3,
        "Sst": 30,
        "COMPUTER": 38,
        "DRAWING": 46,
        "GK": 38,
        "PHYSICALEDUCATION": 49,
        "TOTAL": 253,
        "PRECENTAGE": 56.222222222222214
       },
       {
        "id": "20220805",
        "RollNo": "05",
        "STUDENT": "MUSKAN",
        "FATHER": "GABBAR SINGH",
        "Class": "08",
        "HINDI": 48,
        "ENGLISH": 47,
        "MATHS": 24,
        "SCINCE": 42,
        "Sst": 31,
        "COMPUTER": 49,
        "DRAWING": 43,
        "GK": 49,
        "PHYSICALEDUCATION": 49,
        "TOTAL": 382,
        "PRECENTAGE": 84.88888888888889
       },
       {
        "id": "20220806",
        "RollNo": "06",
        "STUDENT": "VARSHA",
        "FATHER": "RAM PRASAD",
        "Class": "08",
        "HINDI": 25,
        "ENGLISH": 23,
        "MATHS": "A",
        "SCINCE": "A",
        "Sst": "A",
        "COMPUTER": "A",
        "DRAWING": 42,
        "GK": "A",
        "PHYSICALEDUCATION": 50,
        "TOTAL": 140,
        "PRECENTAGE": 31.11111111111111
       },
       {
        "id": "20220807",
        "RollNo": "07",
        "STUDENT": "ANIL",
        "FATHER": "AMAR PRASAD",
        "Class": "08",
        "HINDI": 48,
        "ENGLISH": 49,
        "MATHS": 42,
        "SCINCE": 35,
        "Sst": 40,
        "COMPUTER": 50,
        "DRAWING": 34,
        "GK": 50,
        "PHYSICALEDUCATION": 48,
        "TOTAL": 396,
        "PRECENTAGE": 88
       },
       {
        "id": "20220808",
        "RollNo": "08",
        "STUDENT": "RAGHURAJ",
        "FATHER": "ISHWARI PRASAD",
        "Class": "08",
        "HINDI": 44,
        "ENGLISH": 45,
        "MATHS": 37,
        "SCINCE": 26,
        "Sst": 35,
        "COMPUTER": 50,
        "DRAWING": 40,
        "GK": 50,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 377,
        "PRECENTAGE": 83.77777777777777
       },
       {
        "id": "20220809",
        "RollNo": "09",
        "STUDENT": "PANKAJ",
        "FATHER": "SHIV KUMAR",
        "Class": "08",
        "HINDI": 32,
        "ENGLISH": 17,
        "MATHS": 19,
        "SCINCE": 16,
        "Sst": 27,
        "COMPUTER": 48,
        "DRAWING": 40,
        "GK": 48,
        "PHYSICALEDUCATION": 49,
        "TOTAL": 296,
        "PRECENTAGE": 65.77777777777779
       },
       {
        "id": "20220810",
        "RollNo": "10",
        "STUDENT": "ANSHUL",
        "FATHER": "ATAR SINGH",
        "Class": "08",
        "HINDI": 30,
        "ENGLISH": 11,
        "MATHS": 13,
        "SCINCE": 14,
        "Sst": 22,
        "COMPUTER": 50,
        "DRAWING": 38,
        "GK": 50,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 278,
        "PRECENTAGE": 61.77777777777778
       },
       {
        "id": "20220811",
        "RollNo": "11",
        "STUDENT": "GAURAV",
        "FATHER": "SHAB SINGH",
        "Class": "08",
        "HINDI": 30,
        "ENGLISH": 17,
        "MATHS": 20,
        "SCINCE": 8,
        "Sst": 29,
        "COMPUTER": 48,
        "DRAWING": 36,
        "GK": 48,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 286,
        "PRECENTAGE": 63.55555555555556
       },
       {
        "id": "20220812",
        "RollNo": "12",
        "STUDENT": "KRISHANA",
        "FATHER": "BHAGAVAN SINGH",
        "Class": "08",
        "HINDI": 40,
        "ENGLISH": "A",
        "MATHS": 18,
        "SCINCE": 18,
        "Sst": 29,
        "COMPUTER": 50,
        "DRAWING": "A",
        "GK": 50,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 255,
        "PRECENTAGE": 56.666666666666664
       },
       {
        "id": "20220813",
        "RollNo": "13",
        "STUDENT": "VIVEK",
        "FATHER": "SATYVEER SINGH",
        "Class": "08",
        "HINDI": 33,
        "ENGLISH": 21,
        "MATHS": 26,
        "SCINCE": 12,
        "Sst": 12,
        "COMPUTER": 48,
        "DRAWING": 36,
        "GK": 48,
        "PHYSICALEDUCATION": 49,
        "TOTAL": 285,
        "PRECENTAGE": 63.33333333333333
       },
       {
        "id": "20220814",
        "RollNo": "14",
        "STUDENT": "ABHISHEK",
        "FATHER": "KHAJAN SINGH",
        "Class": "08",
        "HINDI": 34,
        "ENGLISH": 34,
        "MATHS": 32,
        "SCINCE": 36,
        "Sst": 33,
        "COMPUTER": 50,
        "DRAWING": 37,
        "GK": 50,
        "PHYSICALEDUCATION": 49,
        "TOTAL": 355,
        "PRECENTAGE": 78.88888888888889
       },
       {
        "id": "20220815",
        "RollNo": "15",
        "STUDENT": "GAURAV ",
        "FATHER": "BRIJ KISHOR",
        "Class": "08",
        "HINDI": 40,
        "ENGLISH": 18,
        "MATHS": 14,
        "SCINCE": 9,
        "Sst": 25,
        "COMPUTER": 43,
        "DRAWING": 36,
        "GK": 43,
        "PHYSICALEDUCATION": 49,
        "TOTAL": 277,
        "PRECENTAGE": 61.55555555555555
       },
       {
        "id": "20220816",
        "RollNo": "16",
        "STUDENT": "JITENDRA",
        "FATHER": "RAVENDRA SINGH",
        "Class": "08",
        "HINDI": "A",
        "ENGLISH": 35,
        "MATHS": 28,
        "SCINCE": 40,
        "Sst": 35,
        "COMPUTER": 50,
        "DRAWING": 31,
        "GK": 50,
        "PHYSICALEDUCATION": 48,
        "TOTAL": 317,
        "PRECENTAGE": 70.44444444444444
       },
       {
        "id": "20220817",
        "RollNo": "17",
        "STUDENT": "JITENDRA",
        "FATHER": "GYANI RAM",
        "Class": "08",
        "HINDI": 45,
        "ENGLISH": 34,
        "MATHS": 27,
        "SCINCE": 13,
        "Sst": 12,
        "COMPUTER": 45,
        "DRAWING": 38,
        "GK": 45,
        "PHYSICALEDUCATION": 49,
        "TOTAL": 308,
        "PRECENTAGE": 68.44444444444444
       },
       {
        "id": "20220818",
        "RollNo": "18",
        "STUDENT": "AKASH",
        "FATHER": "RAM BABU",
        "Class": "08",
        "HINDI": "A",
        "ENGLISH": 17,
        "MATHS": 13,
        "SCINCE": "A",
        "Sst": 23,
        "COMPUTER": 45,
        "DRAWING": 38,
        "GK": 45,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 231,
        "PRECENTAGE": 51.33333333333333
       },
       {
        "id": "20220819",
        "RollNo": "19",
        "STUDENT": "ASHISH",
        "FATHER": "PRATAP SINGH",
        "Class": "08",
        "HINDI": 46,
        "ENGLISH": 37,
        "MATHS": 28,
        "SCINCE": 33,
        "Sst": 50,
        "COMPUTER": 48,
        "DRAWING": 39,
        "GK": 48,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 379,
        "PRECENTAGE": 84.22222222222221
       },
       {
        "id": "2022"
       },
       {
        "id": "20220401",
        "RollNo": "01",
        "STUDENT": "AMRITA",
        "FATHER": "DHANVAN SINGH",
        "Class": "04",
        "HINDI": 43,
        "ENGLISH": 21,
        "MATHS": 21,
        "SCINCE": 25,
        "Sst": 9,
        "COMPUTER": 37,
        "DRAWING": 30,
        "GK": 24,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 260,
        "PRECENTAGE": 57.77777777777777
       },
       {
        "id": "20220402",
        "RollNo": "02",
        "STUDENT": "DIVYANSHI",
        "FATHER": "SANJAY KUSHWAH",
        "Class": "04",
        "HINDI": 45,
        "ENGLISH": 40,
        "MATHS": 48,
        "SCINCE": 38,
        "Sst": 20,
        "COMPUTER": 28,
        "DRAWING": 35,
        "GK": 34,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 338,
        "PRECENTAGE": 75.1111111111111
       },
       {
        "id": "20220403",
        "RollNo": "03",
        "STUDENT": "BHARATI",
        "FATHER": "PATI RAM",
        "Class": "04",
        "HINDI": 41,
        "ENGLISH": 33,
        "MATHS": 28,
        "SCINCE": 25,
        "Sst": 10,
        "COMPUTER": 18,
        "DRAWING": 35,
        "GK": 38,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 278,
        "PRECENTAGE": 61.77777777777778
       },
       {
        "id": "20220404",
        "RollNo": "04",
        "STUDENT": "SIMMI",
        "FATHER": "RAKESH KUSHWAH",
        "Class": "04",
        "HINDI": 40,
        "ENGLISH": 17,
        "MATHS": 28,
        "SCINCE": 26,
        "Sst": 4,
        "COMPUTER": 22,
        "DRAWING": 35,
        "GK": 10,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 232,
        "PRECENTAGE": 51.55555555555556
       },
       {
        "id": "20220405",
        "RollNo": "05",
        "STUDENT": "KHUSHBOO",
        "FATHER": "RAMPRAKASH",
        "Class": "04",
        "HINDI": 30,
        "ENGLISH": 14,
        "MATHS": 30,
        "SCINCE": 20,
        "Sst": 9,
        "COMPUTER": 28,
        "DRAWING": "A",
        "GK": 30,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 211,
        "PRECENTAGE": 46.88888888888889
       },
       {
        "id": "20220406",
        "RollNo": "06",
        "STUDENT": "RISHU",
        "FATHER": "SUBHASH CHANDRA",
        "Class": "04",
        "HINDI": 40,
        "ENGLISH": 18,
        "MATHS": 36,
        "SCINCE": 20,
        "Sst": 3,
        "COMPUTER": 16,
        "DRAWING": "A",
        "GK": 30,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 213,
        "PRECENTAGE": 47.333333333333336
       },
       {
        "id": "20220407",
        "RollNo": "07",
        "STUDENT": "MAHIMA",
        "FATHER": "RAMDATT",
        "Class": "04",
        "HINDI": 26,
        "ENGLISH": 23,
        "MATHS": 40,
        "SCINCE": 22,
        "Sst": 0,
        "COMPUTER": 14,
        "DRAWING": 35,
        "GK": 30,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 240,
        "PRECENTAGE": 53.333333333333336
       },
       {
        "id": "20220408",
        "RollNo": "08",
        "STUDENT": "SHIVANI",
        "FATHER": "DEVENDRA SINGH",
        "Class": "04",
        "HINDI": 31,
        "ENGLISH": 38,
        "MATHS": 32,
        "SCINCE": 20,
        "Sst": 1,
        "COMPUTER": 22,
        "DRAWING": 30,
        "GK": 36,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 260,
        "PRECENTAGE": 57.77777777777777
       },
       {
        "id": "20220409",
        "RollNo": "09",
        "STUDENT": "RAGINI",
        "FATHER": "SATYA PRAKASH",
        "Class": "04",
        "HINDI": "A",
        "ENGLISH": "A",
        "MATHS": "A",
        "SCINCE": "A",
        "Sst": "A",
        "COMPUTER": "A",
        "DRAWING": "A",
        "GK": "A",
        "PHYSICALEDUCATION": 50,
        "TOTAL": 50,
        "PRECENTAGE": 11.11111111111111
       },
       {
        "id": "20220410",
        "RollNo": "10",
        "STUDENT": "KINJAL",
        "FATHER": "PUSHPENDRA",
        "Class": "04",
        "HINDI": 5,
        "ENGLISH": 34,
        "MATHS": 46,
        "SCINCE": 21,
        "Sst": 0,
        "COMPUTER": 23,
        "GK": 48,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 227,
        "PRECENTAGE": 50.44444444444445
       },
       {
        "id": "20220411",
        "RollNo": "11",
        "STUDENT": "NISHANT",
        "FATHER": "CHOB SINGH",
        "Class": "04",
        "HINDI": 47,
        "ENGLISH": 25,
        "MATHS": 38,
        "SCINCE": 34,
        "Sst": 14,
        "COMPUTER": 32,
        "DRAWING": 35,
        "GK": 39,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 314,
        "PRECENTAGE": 69.77777777777779
       },
       {
        "id": "20220412",
        "RollNo": "12",
        "STUDENT": "ANSHU",
        "FATHER": "DINESH CHANDRA",
        "Class": "04",
        "HINDI": 26,
        "ENGLISH": 27,
        "MATHS": 42,
        "SCINCE": 30,
        "Sst": 11,
        "COMPUTER": 38,
        "DRAWING": 47,
        "GK": 42,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 313,
        "PRECENTAGE": 69.55555555555556
       },
       {
        "id": "20220413",
        "RollNo": "13",
        "STUDENT": "VINAY",
        "FATHER": "SHYAM SINGH",
        "Class": "04",
        "HINDI": 8,
        "ENGLISH": 12,
        "MATHS": 38,
        "SCINCE": 25,
        "Sst": 6,
        "COMPUTER": 9,
        "DRAWING": 30,
        "GK": 42,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 220,
        "PRECENTAGE": 48.888888888888886
       },
       {
        "id": "20220414",
        "RollNo": "14",
        "STUDENT": "NIKHIL",
        "FATHER": "OMPRAKASH",
        "Class": "04",
        "HINDI": 5,
        "ENGLISH": "A",
        "MATHS": 41,
        "SCINCE": 20,
        "Sst": "A",
        "COMPUTER": 14,
        "DRAWING": 40,
        "GK": 28,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 198,
        "PRECENTAGE": 44
       },
       {
        "id": "20220415",
        "RollNo": "15",
        "STUDENT": "YOGENDRA",
        "FATHER": "RAMPRAKASH",
        "Class": "04",
        "HINDI": 28,
        "ENGLISH": 16,
        "MATHS": 22,
        "SCINCE": 20,
        "Sst": 3,
        "COMPUTER": 8,
        "DRAWING": 35,
        "GK": 34,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 216,
        "PRECENTAGE": 48
       },
       {
        "id": "20220416",
        "RollNo": "16",
        "STUDENT": "BRIJESH",
        "FATHER": "POKPAL SINGH",
        "Class": "04",
        "HINDI": 27,
        "ENGLISH": 10,
        "MATHS": 26,
        "SCINCE": 19,
        "Sst": "A",
        "COMPUTER": 11,
        "DRAWING": "A",
        "GK": 30,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 173,
        "PRECENTAGE": 38.44444444444444
       },
       {
        "id": "20220417",
        "RollNo": "17",
        "STUDENT": "MONESH",
        "FATHER": "RAJKUMAR",
        "Class": "04",
        "HINDI": 33,
        "ENGLISH": 17,
        "MATHS": 42,
        "SCINCE": 20,
        "Sst": 18,
        "COMPUTER": 21,
        "DRAWING": 36,
        "GK": 46,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 283,
        "PRECENTAGE": 62.88888888888889
       },
       {
        "id": "20220418",
        "RollNo": "18",
        "STUDENT": "ABHAY",
        "FATHER": "PUNJABI KUSHWAH",
        "Class": "04",
        "HINDI": "A",
        "ENGLISH": 4,
        "MATHS": "A",
        "SCINCE": 15,
        "Sst": "A",
        "COMPUTER": 9,
        "DRAWING": 35,
        "GK": 23,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 136,
        "PRECENTAGE": 30.22222222222222
       },
       {
        "id": "20220419",
        "RollNo": "19",
        "STUDENT": "MOHINEE",
        "FATHER": " SAHDEV SINGH",
        "Class": "04",
        "HINDI": 38,
        "ENGLISH": 17,
        "MATHS": 12,
        "SCINCE": 20,
        "Sst": 4,
        "COMPUTER": 14,
        "DRAWING": 26,
        "GK": 30,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 211,
        "PRECENTAGE": 46.88888888888889
       },
       {
        "id": "20220420",
        "RollNo": "20",
        "STUDENT": "ANJALI -1",
        "FATHER": "PRADEEP KUSHWAHA",
        "Class": "04",
        "HINDI": 41,
        "ENGLISH": 24,
        "MATHS": 42,
        "SCINCE": 19,
        "Sst": 6,
        "COMPUTER": 44,
        "DRAWING": 42,
        "GK": 14,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 282,
        "PRECENTAGE": 62.66666666666667
       },
       {
        "id": "20220421",
        "RollNo": "21",
        "STUDENT": "SANI ",
        "FATHER": "OMPRAKASH",
        "Class": "04",
        "HINDI": 9,
        "ENGLISH": 10,
        "MATHS": 5,
        "SCINCE": 20,
        "Sst": 0,
        "COMPUTER": 4,
        "DRAWING": 30,
        "GK": 20,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 148,
        "PRECENTAGE": 32.88888888888889
       },
       {
        "id": "20220422",
        "RollNo": "22",
        "STUDENT": "ANJALI -2",
        "FATHER": "PINKU SINGH",
        "Class": "04",
        "HINDI": 30,
        "ENGLISH": 10,
        "MATHS": 36,
        "SCINCE": 25,
        "Sst": 3,
        "COMPUTER": 42,
        "DRAWING": 42,
        "GK": 8,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 246,
        "PRECENTAGE": 54.666666666666664
       },
       {
        "id": "2022"
       },
       {
        "id": "20220501",
        "RollNo": "01",
        "STUDENT": "UPASANA",
        "FATHER": "JASWANT SINGH",
        "Class": "05",
        "HINDI": 30,
        "ENGLISH": "A",
        "MATHS": 42,
        "SCINCE": 24,
        "Sst": "A",
        "COMPUTER": 40,
        "DRAWING": 40,
        "GK": 34,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 260,
        "PRECENTAGE": 57.77777777777777
       },
       {
        "id": "20220502",
        "RollNo": "02",
        "STUDENT": "KUSHI",
        "FATHER": "AMAR PRASAD",
        "Class": "05",
        "HINDI": 37,
        "ENGLISH": 10,
        "MATHS": 34,
        "SCINCE": 11,
        "Sst": 15,
        "COMPUTER": 39,
        "DRAWING": 46,
        "GK": 27,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 219,
        "PRECENTAGE": 48.66666666666667
       },
       {
        "id": "20220503",
        "RollNo": "03",
        "STUDENT": "SABNAM",
        "FATHER": "RAFEEK KHAN",
        "Class": "05",
        "HINDI": 15,
        "ENGLISH": 12,
        "MATHS": 37,
        "SCINCE": 4,
        "Sst": 5,
        "COMPUTER": 36,
        "DRAWING": 28,
        "GK": 25,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 162,
        "PRECENTAGE": 36
       },
       {
        "id": "20220504",
        "RollNo": "04",
        "STUDENT": "NISHA",
        "FATHER": "AHAMAD KHAN",
        "Class": "05",
        "HINDI": 18,
        "ENGLISH": 10,
        "MATHS": 34,
        "SCINCE": 12,
        "Sst": 8,
        "COMPUTER": 45,
        "DRAWING": 44,
        "GK": 28,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 199,
        "PRECENTAGE": 44.22222222222222
       },
       {
        "id": "20220505",
        "RollNo": "05",
        "STUDENT": "DIL KUSH",
        "FATHER": "HIMMAT SINGH",
        "Class": "05",
        "HINDI": 20,
        "ENGLISH": 20,
        "MATHS": 32,
        "SCINCE": 16,
        "Sst": 10,
        "COMPUTER": 32,
        "DRAWING": 42,
        "GK": 26,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 198,
        "PRECENTAGE": 44
       },
       {
        "id": "20220506",
        "RollNo": "06",
        "STUDENT": "MOHINI",
        "FATHER": "KEVAL SINGH",
        "Class": "05",
        "HINDI": 0,
        "ENGLISH": 4,
        "MATHS": 31,
        "SCINCE": 10,
        "Sst": 10,
        "COMPUTER": 42,
        "DRAWING": "A",
        "GK": 30,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 127,
        "PRECENTAGE": 28.22222222222222
       },
       {
        "id": "20220507",
        "RollNo": "07",
        "STUDENT": "HIMANSHI",
        "FATHER": "ASHOK KUMAR",
        "Class": "05",
        "HINDI": 27,
        "ENGLISH": 21,
        "MATHS": 47,
        "SCINCE": 32,
        "Sst": 18,
        "COMPUTER": 36,
        "DRAWING": 46,
        "GK": 29,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 256,
        "PRECENTAGE": 56.888888888888886
       },
       {
        "id": "20220508",
        "RollNo": "08",
        "STUDENT": "SHIVANI",
        "FATHER": "MAHAVEER SINGH",
        "Class": "05",
        "HINDI": 10,
        "ENGLISH": 6,
        "MATHS": 31,
        "SCINCE": 12,
        "Sst": 11,
        "COMPUTER": 38,
        "DRAWING": 42,
        "GK": 25,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 175,
        "PRECENTAGE": 38.88888888888889
       },
       {
        "id": "20220509",
        "RollNo": "09",
        "STUDENT": "JAY VEER",
        "FATHER": "MURARI LAL",
        "Class": "05",
        "HINDI": 2,
        "ENGLISH": 7,
        "MATHS": 38,
        "SCINCE": 16,
        "Sst": 7,
        "COMPUTER": 46,
        "DRAWING": 4,
        "GK": 27,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 147,
        "PRECENTAGE": 32.666666666666664
       },
       {
        "id": "20220510",
        "RollNo": "10",
        "STUDENT": "VIVEK",
        "FATHER": "SANJAY",
        "Class": "05",
        "HINDI": 26,
        "ENGLISH": 12,
        "MATHS": 38,
        "SCINCE": 15,
        "Sst": 8,
        "COMPUTER": 44,
        "DRAWING": 44,
        "GK": 37,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 224,
        "PRECENTAGE": 49.77777777777778
       },
       {
        "id": "20220511",
        "RollNo": "11",
        "STUDENT": "PRADEEP",
        "FATHER": "MUNNA LAL",
        "Class": "05",
        "HINDI": 0,
        "ENGLISH": 2,
        "MATHS": 31,
        "SCINCE": 10,
        "Sst": 6,
        "COMPUTER": 42,
        "DRAWING": 40,
        "GK": 37,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 168,
        "PRECENTAGE": 37.333333333333336
       },
       {
        "id": "20220512",
        "RollNo": "12",
        "STUDENT": "ARUN",
        "FATHER": "RAJENDRA SINGH",
        "Class": "05",
        "HINDI": 8,
        "ENGLISH": 12,
        "MATHS": 33,
        "SCINCE": 14,
        "Sst": 10,
        "COMPUTER": 47,
        "DRAWING": 38,
        "GK": 37,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 199,
        "PRECENTAGE": 44.22222222222222
       },
       {
        "id": "20220513",
        "RollNo": "13",
        "STUDENT": "ELESH",
        "FATHER": "HORI LAL",
        "Class": "05",
        "HINDI": 7,
        "ENGLISH": 4,
        "MATHS": 32,
        "SCINCE": 12,
        "Sst": 8,
        "COMPUTER": 43,
        "DRAWING": 38,
        "GK": "A",
        "PHYSICALEDUCATION": 50,
        "TOTAL": 144,
        "PRECENTAGE": 32
       },
       {
        "id": "20220514",
        "RollNo": "14",
        "STUDENT": "SANI",
        "FATHER": "MUNNA LAL",
        "Class": "05",
        "HINDI": 0,
        "ENGLISH": 2,
        "MATHS": 36,
        "SCINCE": 6,
        "Sst": 9,
        "COMPUTER": 45,
        "DRAWING": 2,
        "GK": 18,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 118,
        "PRECENTAGE": 26.222222222222225
       },
       {
        "id": "20220515",
        "RollNo": "15",
        "STUDENT": "KRISHNA",
        "FATHER": "LATIT",
        "Class": "05",
        "HINDI": 0,
        "ENGLISH": 2,
        "MATHS": 32,
        "SCINCE": 14,
        "Sst": 2,
        "COMPUTER": 32,
        "DRAWING": 14,
        "GK": 26,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 122,
        "PRECENTAGE": 27.111111111111114
       },
       {
        "id": "20220516",
        "RollNo": "16",
        "STUDENT": "RASHID",
        "FATHER": "SADEER KHAN",
        "Class": "05",
        "HINDI": 0,
        "ENGLISH": 0,
        "MATHS": 35,
        "SCINCE": 14,
        "Sst": 5,
        "COMPUTER": 33,
        "DRAWING": 40,
        "GK": 28,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 155,
        "PRECENTAGE": 34.44444444444444
       },
       {
        "id": "20220517",
        "RollNo": "17",
        "STUDENT": "KULDEEP",
        "FATHER": "ASHOK KUMAR",
        "Class": "05",
        "HINDI": 14,
        "ENGLISH": 7,
        "MATHS": 36,
        "SCINCE": 14,
        "Sst": 2,
        "COMPUTER": 45,
        "DRAWING": 48,
        "GK": 19,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 185,
        "PRECENTAGE": 41.11111111111111
       },
       {
        "id": "20220518",
        "RollNo": "18",
        "STUDENT": "ANKIT",
        "FATHER": "KALICHARAN",
        "Class": "05",
        "HINDI": 10,
        "ENGLISH": 9,
        "MATHS": 32,
        "SCINCE": 10,
        "Sst": 3,
        "COMPUTER": 32,
        "DRAWING": 10,
        "GK": "A",
        "PHYSICALEDUCATION": 50,
        "TOTAL": 106,
        "PRECENTAGE": 23.555555555555554
       },
       {
        "id": "20220519",
        "RollNo": "19",
        "STUDENT": "KANHA",
        "FATHER": "LALIT",
        "Class": "05",
        "HINDI": 27,
        "ENGLISH": 9,
        "MATHS": 45,
        "SCINCE": 14,
        "Sst": 8,
        "COMPUTER": 31,
        "DRAWING": 42,
        "GK": 29,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 205,
        "PRECENTAGE": 45.55555555555556
       },
       {
        "id": "20220520",
        "RollNo": "20",
        "STUDENT": "ANUJ",
        "FATHER": "RAM DATT",
        "Class": "05",
        "HINDI": 30,
        "ENGLISH": 1,
        "MATHS": 31,
        "SCINCE": 14,
        "Sst": 0,
        "COMPUTER": 45,
        "DRAWING": 46,
        "GK": 24,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 191,
        "PRECENTAGE": 42.44444444444444
       },
       {
        "id": "20220521",
        "RollNo": "21",
        "STUDENT": "MONU",
        "FATHER": " KEBAL SINGH",
        "Class": "05",
        "HINDI": 10,
        "ENGLISH": 5,
        "MATHS": 33,
        "SCINCE": 18,
        "Sst": 4,
        "COMPUTER": 32,
        "DRAWING": 26,
        "GK": 21,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 149,
        "PRECENTAGE": 33.111111111111114
       },
       {
        "id": "20220522",
        "RollNo": "22",
        "STUDENT": "SANI",
        "FATHER": "KEVAL SINGH",
        "Class": "05",
        "HINDI": 5,
        "ENGLISH": 11,
        "MATHS": 31,
        "SCINCE": "A",
        "Sst": "A",
        "COMPUTER": 33,
        "DRAWING": 31,
        "GK": "A",
        "PHYSICALEDUCATION": 50,
        "TOTAL": 111,
        "PRECENTAGE": 24.666666666666668
       },
       {
        "id": "20220523",
        "RollNo": "23",
        "STUDENT": "ANUJ",
        "FATHER": "HEERA SINGH",
        "Class": "05",
        "HINDI": "A",
        "ENGLISH": 11,
        "MATHS": 34,
        "SCINCE": 18,
        "Sst": 15,
        "COMPUTER": 45,
        "DRAWING": 48,
        "GK": 18,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 189,
        "PRECENTAGE": 42
       },
       {
        "id": "20220524",
        "RollNo": "24",
        "STUDENT": "MOHIT",
        "FATHER": "JAY PAL",
        "Class": "05",
        "HINDI": 5,
        "ENGLISH": 3,
        "MATHS": 32,
        "SCINCE": 10,
        "Sst": 5,
        "COMPUTER": 35,
        "DRAWING": 2,
        "GK": 23,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 115,
        "PRECENTAGE": 25.555555555555554
       },
       {
        "id": "2022"
       },
       {
        "id": "20220201",
        "RollNo": "01",
        "STUDENT": "BHAWANA",
        "FATHER": "CHDAMME LAL",
        "Class": "02",
        "HINDI": 49,
        "ENGLISH": 50,
        "MATHS": 47,
        "SCINCE": 49,
        "COMPUTER": 50,
        "DRAWING": 50,
        "GK": 50,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 395,
        "PRECENTAGE": 98.75
       },
       {
        "id": "20220202",
        "RollNo": "02",
        "STUDENT": "RAGINEE",
        "Class": "02",
        "HINDI": 18,
        "ENGLISH": 19,
        "MATHS": 23,
        "SCINCE": 30,
        "COMPUTER": 18,
        "DRAWING": 44,
        "GK": 25,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 227,
        "PRECENTAGE": 56.75
       },
       {
        "id": "20220203",
        "RollNo": "03",
        "STUDENT": "RITU",
        "Class": "02",
        "HINDI": 46,
        "ENGLISH": 42,
        "MATHS": 45,
        "SCINCE": 37,
        "COMPUTER": 30,
        "DRAWING": 30,
        "GK": 50,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 330,
        "PRECENTAGE": 82.5
       },
       {
        "id": "20220204",
        "RollNo": "04",
        "STUDENT": "ANJALI",
        "Class": "02",
        "HINDI": 9,
        "ENGLISH": 7,
        "MATHS": 34,
        "SCINCE": 30,
        "COMPUTER": "A",
        "DRAWING": 25,
        "GK": 40,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 195,
        "PRECENTAGE": 48.75
       },
       {
        "id": "20220205",
        "RollNo": "05",
        "STUDENT": "AMAN",
        "Class": "02",
        "HINDI": 37,
        "ENGLISH": 45,
        "MATHS": 38,
        "SCINCE": 36,
        "COMPUTER": 32,
        "DRAWING": 48,
        "GK": 41,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 327,
        "PRECENTAGE": 81.75
       },
       {
        "id": "20220206",
        "RollNo": "06",
        "STUDENT": "SARTHAK",
        "Class": "02",
        "HINDI": "A",
        "ENGLISH": 50,
        "MATHS": 50,
        "SCINCE": 49,
        "COMPUTER": 46,
        "DRAWING": 44,
        "GK": "A",
        "PHYSICALEDUCATION": 50,
        "TOTAL": 289,
        "PRECENTAGE": 72.25
       },
       {
        "id": "20220207",
        "RollNo": "07",
        "STUDENT": "YASH",
        "Class": "02",
        "HINDI": 48,
        "ENGLISH": 48,
        "MATHS": 43,
        "SCINCE": 36,
        "COMPUTER": 50,
        "DRAWING": 49,
        "GK": 40,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 364,
        "PRECENTAGE": 91
       },
       {
        "id": "20220208",
        "RollNo": "08",
        "STUDENT": "DEEPAK",
        "Class": "02",
        "HINDI": 41,
        "ENGLISH": 34,
        "MATHS": 42,
        "SCINCE": 45,
        "COMPUTER": 20,
        "DRAWING": 30,
        "GK": 50,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 312,
        "PRECENTAGE": 78
       },
       {
        "id": "20220209",
        "RollNo": "09",
        "STUDENT": "SANDEEP",
        "Class": "02",
        "HINDI": 49,
        "ENGLISH": 46,
        "MATHS": 47,
        "SCINCE": 47,
        "COMPUTER": 18,
        "DRAWING": 48,
        "GK": 40,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 345,
        "PRECENTAGE": 86.25
       },
       {
        "id": "20220210",
        "RollNo": "10",
        "STUDENT": "PANKAJ",
        "Class": "02",
        "HINDI": 49,
        "ENGLISH": 48,
        "MATHS": 45,
        "SCINCE": 45,
        "COMPUTER": 30,
        "DRAWING": 47,
        "GK": 50,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 364,
        "PRECENTAGE": 91
       },
       {
        "id": "20220211",
        "RollNo": "11",
        "STUDENT": "MOHIT",
        "Class": "02",
        "HINDI": 46,
        "ENGLISH": 42,
        "MATHS": 37,
        "SCINCE": 37,
        "COMPUTER": 36,
        "DRAWING": 47,
        "GK": 45,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 340,
        "PRECENTAGE": 85
       },
       {
        "id": "20220212",
        "RollNo": "12",
        "STUDENT": "ANSHUL",
        "Class": "02",
        "HINDI": 39,
        "ENGLISH": 20,
        "MATHS": 44,
        "SCINCE": 35,
        "COMPUTER": 25,
        "DRAWING": 41,
        "GK": 40,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 294,
        "PRECENTAGE": 73.5
       },
       {
        "id": "20220213",
        "RollNo": "13",
        "STUDENT": "PRINCE",
        "Class": "02",
        "HINDI": 35,
        "ENGLISH": 38,
        "MATHS": 42,
        "SCINCE": 48,
        "COMPUTER": 38,
        "DRAWING": 46,
        "GK": 45,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 342,
        "PRECENTAGE": 85.5
       },
       {
        "id": "20220214",
        "RollNo": "14",
        "STUDENT": "AYUSH",
        "Class": "02",
        "HINDI": 21,
        "ENGLISH": 33,
        "MATHS": 40,
        "SCINCE": 40,
        "COMPUTER": 11,
        "DRAWING": 47,
        "GK": 45,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 287,
        "PRECENTAGE": 71.75
       },
       {
        "id": "20220215",
        "RollNo": "15",
        "STUDENT": "AJAY",
        "Class": "02",
        "HINDI": 3,
        "ENGLISH": 33,
        "MATHS": 45,
        "SCINCE": 32,
        "COMPUTER": 11,
        "DRAWING": 40,
        "GK": 35,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 249,
        "PRECENTAGE": 62.25000000000001
       },
       {
        "id": "20220216",
        "RollNo": "16",
        "STUDENT": "MANEESH",
        "Class": "02",
        "HINDI": 14,
        "ENGLISH": 19,
        "MATHS": 48,
        "SCINCE": 41,
        "COMPUTER": 8,
        "DRAWING": 42,
        "GK": 40,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 262,
        "PRECENTAGE": 65.5
       },
       {
        "id": "20220217",
        "RollNo": "17",
        "STUDENT": "PIYUSH",
        "Class": "02",
        "HINDI": 48,
        "ENGLISH": 42,
        "MATHS": 27,
        "SCINCE": 40,
        "COMPUTER": 47,
        "DRAWING": 44,
        "GK": 50,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 348,
        "PRECENTAGE": 87
       },
       {
        "id": "20220218",
        "RollNo": "18",
        "STUDENT": "SARAS",
        "Class": "02",
        "HINDI": 48,
        "ENGLISH": 37,
        "MATHS": 36,
        "SCINCE": 32,
        "COMPUTER": 45,
        "DRAWING": 43,
        "GK": 50,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 341,
        "PRECENTAGE": 85.25
       },
       {
        "id": "20220219",
        "RollNo": "19",
        "STUDENT": "BHUPENDRA",
        "Class": "02",
        "HINDI": 49,
        "ENGLISH": 39,
        "MATHS": 45,
        "SCINCE": 30,
        "COMPUTER": 38,
        "DRAWING": 50,
        "GK": 40,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 341,
        "PRECENTAGE": 85.25
       },
       {
        "id": "20220220",
        "RollNo": "20",
        "STUDENT": "KANHA",
        "Class": "02",
        "HINDI": 10,
        "ENGLISH": 29,
        "MATHS": 40,
        "SCINCE": 39,
        "COMPUTER": 25,
        "DRAWING": 36,
        "GK": 40,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 269,
        "PRECENTAGE": 67.25
       },
       {
        "id": "20220221",
        "RollNo": "21",
        "STUDENT": "PREMVEER",
        "Class": "02",
        "HINDI": "A    ",
        "ENGLISH": "A    ",
        "MATHS": "A    ",
        "SCINCE": "A    ",
        "COMPUTER": "A    ",
        "DRAWING": "A    ",
        "GK": "A    ",
        "PHYSICALEDUCATION": 50,
        "TOTAL": 50,
        "PRECENTAGE": 12.5
       },
       {
        "id": "20220222",
        "RollNo": "22",
        "STUDENT": "RIYA",
        "Class": "02",
        "HINDI": 49,
        "ENGLISH": 49,
        "MATHS": 44,
        "SCINCE": 46,
        "COMPUTER": 45,
        "DRAWING": 50,
        "GK": 40,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 373,
        "PRECENTAGE": 93.25
       },
       {
        "id": "20220223",
        "RollNo": "23",
        "STUDENT": "BHOLA",
        "Class": "02",
        "HINDI": 30,
        "ENGLISH": 21,
        "MATHS": 40,
        "SCINCE": 31,
        "COMPUTER": 17,
        "DRAWING": 37,
        "GK": 40,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 266,
        "PRECENTAGE": 66.5
       },
       {
        "id": "20220224",
        "RollNo": "24",
        "STUDENT": "RAJ",
        "Class": "02",
        "HINDI": 3,
        "ENGLISH": 30,
        "MATHS": 49,
        "SCINCE": 35,
        "COMPUTER": 31,
        "DRAWING": 40,
        "GK": 25,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 263,
        "PRECENTAGE": 65.75
       },
       {
        "id": "20220225",
        "RollNo": "25",
        "STUDENT": "SHIVAM",
        "Class": "02",
        "HINDI": 42,
        "ENGLISH": 35,
        "MATHS": 45,
        "SCINCE": 35,
        "COMPUTER": 17,
        "DRAWING": 45,
        "GK": 40,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 309,
        "PRECENTAGE": 77.25
       },
       {
        "id": "20220226",
        "RollNo": "26",
        "STUDENT": "MANEESH",
        "Class": "02",
        "HINDI": 38,
        "ENGLISH": 38,
        "MATHS": "A",
        "SCINCE": 32,
        "COMPUTER": 22,
        "DRAWING": 36,
        "GK": 30,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 246,
        "PRECENTAGE": 61.5
       },
       {
        "id": "20220227",
        "RollNo": "27",
        "STUDENT": "JITENDRA",
        "Class": "02",
        "HINDI": 28,
        "ENGLISH": 36,
        "MATHS": 50,
        "SCINCE": 34,
        "COMPUTER": 30,
        "DRAWING": 30,
        "GK": 50,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 308,
        "PRECENTAGE": 77
       },
       {
        "id": "20220228",
        "RollNo": "28",
        "STUDENT": "YOGI",
        "Class": "02",
        "HINDI": 8,
        "ENGLISH": 3,
        "MATHS": 17,
        "SCINCE": 42,
        "COMPUTER": 30,
        "DRAWING": 16,
        "GK": 35,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 201,
        "PRECENTAGE": 50.24999999999999
       },
       {
        "id": "20220229",
        "RollNo": "29",
        "STUDENT": "MANEESHA",
        "Class": "02",
        "HINDI": 46,
        "ENGLISH": 30,
        "MATHS": 38,
        "SCINCE": 25,
        "COMPUTER": 20,
        "DRAWING": 40,
        "GK": 30,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 279,
        "PRECENTAGE": 69.75
       },
       {
        "id": "20220230",
        "RollNo": "30",
        "STUDENT": "BANDANA",
        "Class": "02",
        "HINDI": 45,
        "ENGLISH": 32,
        "MATHS": 39,
        "SCINCE": 32,
        "COMPUTER": 29,
        "DRAWING": 42,
        "GK": 31,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 300,
        "PRECENTAGE": 75
       },
       {
        "id": "20220231",
        "RollNo": "31",
        "STUDENT": "NIRAJ",
        "Class": "02",
        "HINDI": 31,
        "ENGLISH": 37,
        "MATHS": 43,
        "SCINCE": 43,
        "COMPUTER": 24,
        "DRAWING": 42,
        "GK": 50,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 320,
        "PRECENTAGE": 80
       },
       {
        "id": "20220232",
        "RollNo": "32",
        "STUDENT": "ARUN",
        "Class": "02",
        "HINDI": 48,
        "ENGLISH": 30,
        "MATHS": 45,
        "SCINCE": 21,
        "COMPUTER": 40,
        "DRAWING": 18,
        "GK": 50,
        "PHYSICALEDUCATION": 50,
        "TOTAL": 302,
        "PRECENTAGE": 75.5
       },
       {
        "id": "2022"
       },
       {
        "id": "20220301",
        "RollNo": "01",
        "STUDENT": "DIVYANSHI",
        "FATHER": "DINESH",
        "Class": "03",
        "HINDI": 50,
        "ENGLISH": 36,
        "SCINCE": 50,
        "COMPUTER": 42,
        "DRAWING": 46,
        "GK": 45,
        "PHYSICALEDUCATION": 45,
        "TOTAL": 314,
        "PRECENTAGE": 78.5
       },
       {
        "id": "20220302",
        "RollNo": "02",
        "STUDENT": "DEEKSHA",
        "FATHER": "ASHOK",
        "Class": "03",
        "HINDI": 34,
        "ENGLISH": 29,
        "SCINCE": 29,
        "COMPUTER": 46,
        "DRAWING": 46,
        "GK": 45,
        "PHYSICALEDUCATION": 47,
        "TOTAL": 276,
        "PRECENTAGE": 69
       },
       {
        "id": "20220303",
        "RollNo": "03",
        "STUDENT": "SANDHYA",
        "FATHER": "DORI LAL",
        "Class": "03",
        "HINDI": 45,
        "ENGLISH": 43,
        "SCINCE": 50,
        "COMPUTER": 48,
        "DRAWING": 47,
        "GK": 47,
        "PHYSICALEDUCATION": 47,
        "TOTAL": 327,
        "PRECENTAGE": 81.75
       },
       {
        "id": "20220304",
        "RollNo": "04",
        "STUDENT": "RONAK",
        "FATHER": "RAKESH",
        "Class": "03",
        "HINDI": 38,
        "ENGLISH": 28,
        "SCINCE": 45,
        "COMPUTER": 48,
        "DRAWING": 47,
        "GK": 48,
        "PHYSICALEDUCATION": 49,
        "TOTAL": 303,
        "PRECENTAGE": 75.75
       },
       {
        "id": "20220305",
        "RollNo": "05",
        "STUDENT": "KANAK",
        "FATHER": "SURENDRA",
        "Class": "03",
        "HINDI": 27,
        "ENGLISH": 33,
        "SCINCE": 42,
        "COMPUTER": 46,
        "DRAWING": 47,
        "GK": 46,
        "PHYSICALEDUCATION": 49,
        "TOTAL": 290,
        "PRECENTAGE": 72.5
       },
       {
        "id": "20220306",
        "RollNo": "06",
        "STUDENT": "SAPANA",
        "FATHER": "VIRISINGH",
        "Class": "03",
        "HINDI": 38,
        "ENGLISH": 20,
        "SCINCE": 40,
        "COMPUTER": 18,
        "DRAWING": 46,
        "GK": 46,
        "PHYSICALEDUCATION": 40,
        "TOTAL": 248,
        "PRECENTAGE": 62
       },
       {
        "id": "20220307",
        "RollNo": "07",
        "STUDENT": "MINAKSHI",
        "FATHER": "HIMMAT SINGH",
        "Class": "03",
        "HINDI": 15,
        "ENGLISH": 21,
        "SCINCE": 33,
        "COMPUTER": 44,
        "DRAWING": 44,
        "GK": 45,
        "PHYSICALEDUCATION": 45,
        "TOTAL": 247,
        "PRECENTAGE": 61.75000000000001
       },
       {
        "id": "20220308",
        "RollNo": "08",
        "STUDENT": "VARSHA",
        "FATHER": "BHUPENDRA SINGH",
        "Class": "03",
        "HINDI": 27,
        "ENGLISH": 31,
        "SCINCE": 33,
        "COMPUTER": 39,
        "DRAWING": 46,
        "GK": 45,
        "PHYSICALEDUCATION": 45,
        "TOTAL": 266,
        "PRECENTAGE": 66.5
       },
       {
        "id": "20220309",
        "RollNo": "09",
        "STUDENT": "KAMINI",
        "FATHER": "DEVENDRA",
        "Class": "03",
        "HINDI": 35,
        "ENGLISH": 25,
        "SCINCE": 44,
        "COMPUTER": 44,
        "DRAWING": 47,
        "GK": 48,
        "PHYSICALEDUCATION": 49,
        "TOTAL": 292,
        "PRECENTAGE": 73
       },
       {
        "id": "20220310",
        "RollNo": "10",
        "STUDENT": "CHANCHAL",
        "FATHER": "POP SINGH",
        "Class": "03",
        "HINDI": 25,
        "ENGLISH": 40,
        "SCINCE": 42,
        "COMPUTER": 18,
        "DRAWING": 45,
        "GK": 44,
        "PHYSICALEDUCATION": 38,
        "TOTAL": 252,
        "PRECENTAGE": 63
       },
       {
        "id": "20220311",
        "RollNo": "11",
        "STUDENT": "SAURAV",
        "FATHER": "JASVANT SINGH",
        "Class": "03",
        "HINDI": 25,
        "ENGLISH": 26,
        "SCINCE": 45,
        "COMPUTER": 20,
        "DRAWING": 44,
        "GK": 45,
        "PHYSICALEDUCATION": 42,
        "TOTAL": 247,
        "PRECENTAGE": 61.75000000000001
       },
       {
        "id": "20220312",
        "RollNo": "12",
        "STUDENT": "HARI KANT",
        "FATHER": "POKH PAL",
        "Class": "03",
        "HINDI": 22,
        "ENGLISH": 19,
        "SCINCE": 30,
        "COMPUTER": 22,
        "DRAWING": 42,
        "GK": 44,
        "PHYSICALEDUCATION": 29,
        "TOTAL": 208,
        "PRECENTAGE": 52
       },
       {
        "id": "20220313",
        "RollNo": "13",
        "STUDENT": "HARSH",
        "FATHER": "NAVAL KISHOR",
        "Class": "03",
        "HINDI": 18,
        "ENGLISH": 35,
        "SCINCE": 43,
        "COMPUTER": 40,
        "DRAWING": 47,
        "GK": 48,
        "PHYSICALEDUCATION": 47,
        "TOTAL": 278,
        "PRECENTAGE": 69.5
       },
       {
        "id": "20220314",
        "RollNo": "14",
        "STUDENT": "TEJ PRAKASH",
        "FATHER": "SUBEDAR",
        "Class": "03",
        "HINDI": 26,
        "ENGLISH": 19,
        "SCINCE": 44,
        "COMPUTER": 34,
        "DRAWING": 46,
        "GK": 48,
        "PHYSICALEDUCATION": 44,
        "TOTAL": 261,
        "PRECENTAGE": 65.25
       },
       {
        "id": "20220315",
        "RollNo": "15",
        "STUDENT": "LOKESH",
        "FATHER": "ATAR SINGH",
        "Class": "03",
        "HINDI": 21,
        "ENGLISH": 18,
        "SCINCE": 28,
        "COMPUTER": 32,
        "DRAWING": 46,
        "GK": 45,
        "PHYSICALEDUCATION": "A",
        "TOTAL": 190,
        "PRECENTAGE": 47.5
       },
       {
        "id": "20220316",
        "RollNo": "16",
        "STUDENT": "VINEET",
        "FATHER": "SOM VEER ",
        "Class": "03",
        "HINDI": 0,
        "ENGLISH": 10,
        "SCINCE": "A",
        "COMPUTER": 23,
        "DRAWING": 45,
        "GK": 46,
        "PHYSICALEDUCATION": 38,
        "TOTAL": 162,
        "PRECENTAGE": 40.5
       },
       {
        "id": "20220317",
        "RollNo": "17",
        "STUDENT": "KUNAL",
        "FATHER": "DINESH ",
        "Class": "03",
        "HINDI": 7,
        "ENGLISH": 25,
        "SCINCE": 28,
        "COMPUTER": 23,
        "DRAWING": 45,
        "GK": 45,
        "PHYSICALEDUCATION": 45,
        "TOTAL": 218,
        "PRECENTAGE": 54.50000000000001
       },
       {
        "id": "20220318",
        "RollNo": "18",
        "STUDENT": "JEESAN",
        "FATHER": "AHAMAD KHAN",
        "Class": "03",
        "HINDI": 25,
        "ENGLISH": "A",
        "SCINCE": 30,
        "COMPUTER": 30,
        "DRAWING": 46,
        "GK": 45,
        "PHYSICALEDUCATION": 41,
        "TOTAL": 217,
        "PRECENTAGE": 54.25
       },
       {
        "id": "20220319",
        "RollNo": "19",
        "STUDENT": "DILSAD",
        "FATHER": "ZAMIL KHAL ",
        "Class": "03",
        "HINDI": 35,
        "ENGLISH": 20,
        "SCINCE": 37,
        "COMPUTER": 42,
        "DRAWING": 48,
        "GK": 48,
        "PHYSICALEDUCATION": 47,
        "TOTAL": 277,
        "PRECENTAGE": 69.25
       },
       {
        "id": "20220320",
        "RollNo": "20",
        "STUDENT": "AYUSH",
        "FATHER": "MOHAN SINGH",
        "Class": "03",
        "HINDI": 18,
        "ENGLISH": 20,
        "SCINCE": 43,
        "COMPUTER": 34,
        "DRAWING": 47,
        "GK": 47,
        "PHYSICALEDUCATION": 42,
        "TOTAL": 251,
        "PRECENTAGE": 62.74999999999999
       },
       {
        "id": "20220321",
        "RollNo": "21",
        "STUDENT": "DEEPAK",
        "FATHER": "LAKHAN SINGH",
        "Class": "03",
        "HINDI": 24,
        "ENGLISH": 17,
        "SCINCE": 33,
        "COMPUTER": 0,
        "DRAWING": 46,
        "GK": 45,
        "PHYSICALEDUCATION": 33,
        "TOTAL": 198,
        "PRECENTAGE": 49.5
       },
       {
        "id": "20220322",
        "RollNo": "22",
        "STUDENT": "ASHIK",
        "FATHER": "HIMMAT SINGH",
        "Class": "03",
        "HINDI": 8,
        "ENGLISH": 28,
        "SCINCE": 20,
        "COMPUTER": 43,
        "DRAWING": 45,
        "GK": 45,
        "PHYSICALEDUCATION": 23,
        "TOTAL": 212,
        "PRECENTAGE": 53
       },
       {
        "id": "20220323",
        "RollNo": "23",
        "STUDENT": "LUCCKY",
        "FATHER": "HARENDRA SINGH",
        "Class": "03",
        "HINDI": 21,
        "ENGLISH": 39,
        "SCINCE": 33,
        "COMPUTER": 49,
        "DRAWING": 47,
        "GK": 46,
        "PHYSICALEDUCATION": 45,
        "TOTAL": 280,
        "PRECENTAGE": 70
       },
       {
        "id": "20220324",
        "RollNo": "24",
        "STUDENT": "PIYUSH",
        "FATHER": "NEERAJ",
        "Class": "03",
        "HINDI": 14,
        "ENGLISH": 31,
        "SCINCE": 28,
        "COMPUTER": 24,
        "DRAWING": 47,
        "GK": 46,
        "PHYSICALEDUCATION": 30,
        "TOTAL": 220,
        "PRECENTAGE": 55.00000000000001
       },
       {
        "id": "20220325",
        "RollNo": "25",
        "STUDENT": "ROHIT",
        "FATHER": "DEVENDRA",
        "Class": "03",
        "HINDI": 47,
        "ENGLISH": 30,
        "SCINCE": 48,
        "COMPUTER": 40,
        "DRAWING": 48,
        "GK": 49,
        "PHYSICALEDUCATION": 49,
        "TOTAL": 311,
        "PRECENTAGE": 77.75
       },
       {
        "id": "20220326",
        "RollNo": "26",
        "STUDENT": "ANRAV",
        "FATHER": "HEERA SINGH",
        "Class": "03",
        "HINDI": 18,
        "ENGLISH": 41,
        "SCINCE": 34,
        "COMPUTER": 44,
        "DRAWING": 45,
        "GK": 45,
        "PHYSICALEDUCATION": 36,
        "TOTAL": 263,
        "PRECENTAGE": 65.75
       },
       {
        "id": "20220327",
        "RollNo": "27",
        "STUDENT": "OM PAL ",
        "FATHER": "BHAGIRATH",
        "Class": "03",
        "HINDI": 5,
        "ENGLISH": 30,
        "SCINCE": 29,
        "COMPUTER": 0,
        "DRAWING": 46,
        "GK": 45,
        "PHYSICALEDUCATION": 37,
        "TOTAL": 192,
        "PRECENTAGE": 48
       },
       {
        "id": "20220328",
        "RollNo": "28",
        "STUDENT": "HARDESH",
        "FATHER": "KAMAL SINGH",
        "Class": "03",
        "HINDI": 49,
        "ENGLISH": 35,
        "SCINCE": 48,
        "COMPUTER": 48,
        "DRAWING": 49,
        "GK": 48,
        "PHYSICALEDUCATION": 49,
        "TOTAL": 326,
        "PRECENTAGE": 81.5
       },
       {
        "id": "20220329",
        "RollNo": "29",
        "STUDENT": "ARYAN",
        "FATHER": "NAVAL KISHOR",
        "Class": "03",
        "HINDI": 3,
        "ENGLISH": 23,
        "SCINCE": 10,
        "COMPUTER": 2,
        "DRAWING": 45,
        "GK": 40,
        "PHYSICALEDUCATION": 7,
        "TOTAL": 130,
        "PRECENTAGE": 32.5
       },
       {
        "id": "20220330",
        "RollNo": "30",
        "STUDENT": "RAVI",
        "FATHER": "LAKHAN SINGH",
        "Class": "03",
        "HINDI": 3,
        "ENGLISH": "A",
        "SCINCE": 30,
        "COMPUTER": "A",
        "DRAWING": "A",
        "GK": "A",
        "PHYSICALEDUCATION": "A",
        "TOTAL": 33,
        "PRECENTAGE": 8.25
       },
       {
        "id": "2022"
       },
       {
        "id": "20220601",
        "RollNo": "01",
        "STUDENT": "ABHISEK",
        "FATHER": "SHRI BHAGAVAN",
        "Class": "06",
        "HINDI": 30,
        "ENGLISH": 33,
        "MATHS": 37,
        "SCINCE": 14,
        "Sst": 23,
        "COMPUTER": 26,
        "DRAWING": 31,
        "GK": 37,
        "PHYSICALEDUCATION": 47,
        "TOTAL": 278,
        "PRECENTAGE": 61.77777777777778
       },
       {
        "id": "20220602",
        "RollNo": "02",
        "STUDENT": "DAYA",
        "FATHER": "SHYAM SUNDRA ",
        "Class": "06",
        "HINDI": 35,
        "ENGLISH": 27,
        "MATHS": 39,
        "SCINCE": 27,
        "Sst": 32,
        "COMPUTER": 28,
        "DRAWING": 21,
        "GK": 40,
        "PHYSICALEDUCATION": 46,
        "TOTAL": 295,
        "PRECENTAGE": 65.55555555555556
       },
       {
        "id": "20220603",
        "RollNo": "03",
        "STUDENT": "DEEKSHA",
        "FATHER": "HARENDRA",
        "Class": "06",
        "HINDI": 43,
        "ENGLISH": 22,
        "MATHS": 31,
        "SCINCE": 34,
        "Sst": 31,
        "COMPUTER": 28,
        "DRAWING": 18,
        "GK": 45,
        "PHYSICALEDUCATION": 49,
        "TOTAL": 301,
        "PRECENTAGE": 66.88888888888889
       },
       {
        "id": "20220604",
        "RollNo": "04",
        "STUDENT": "GAURAV",
        "FATHER": "MAHENDRA",
        "Class": "06",
        "HINDI": 47,
        "ENGLISH": 38,
        "MATHS": "A",
        "SCINCE": 38,
        "Sst": 28,
        "COMPUTER": 26,
        "DRAWING": 33,
        "GK": 38,
        "PHYSICALEDUCATION": 49,
        "TOTAL": 297,
        "PRECENTAGE": 66
       },
       {
        "id": "20220605",
        "RollNo": "05",
        "STUDENT": "JAGDEESH",
        "FATHER": "KESHAV",
        "Class": "06",
        "HINDI": 49,
        "ENGLISH": 40,
        "MATHS": 38,
        "SCINCE": 37,
        "Sst": 45,
        "COMPUTER": 16,
        "DRAWING": 28,
        "GK": 38,
        "PHYSICALEDUCATION": 49,
        "TOTAL": 340,
        "PRECENTAGE": 75.55555555555556
       },
       {
        "id": "20220606",
        "RollNo": "06",
        "STUDENT": "JOYTI",
        "FATHER": "EVARAN SINGH",
        "Class": "06",
        "HINDI": 49,
        "ENGLISH": 40,
        "MATHS": 43,
        "SCINCE": 32,
        "Sst": 32,
        "COMPUTER": 27,
        "DRAWING": 27,
        "GK": 48,
        "PHYSICALEDUCATION": 48,
        "TOTAL": 346,
        "PRECENTAGE": 76.88888888888889
       },
       {
        "id": "20220607",
        "RollNo": "07",
        "STUDENT": "KHUSHI",
        "FATHER": "RAM PRAKSH",
        "Class": "06",
        "HINDI": 40,
        "ENGLISH": 28,
        "MATHS": 42,
        "SCINCE": 36,
        "Sst": 35,
        "COMPUTER": 26,
        "DRAWING": 24,
        "GK": 48,
        "PHYSICALEDUCATION": 45,
        "TOTAL": 324,
        "PRECENTAGE": 72
       },
       {
        "id": "20220608",
        "RollNo": "08",
        "STUDENT": "LUCCKY",
        "FATHER": "GABBAR SINGH",
        "Class": "06",
        "HINDI": 48,
        "ENGLISH": 39,
        "MATHS": 37,
        "SCINCE": 36,
        "Sst": 41,
        "COMPUTER": 30,
        "DRAWING": 33,
        "GK": 36,
        "PHYSICALEDUCATION": 47,
        "TOTAL": 347,
        "PRECENTAGE": 77.11111111111111
       },
       {
        "id": "20220609",
        "RollNo": "09",
        "STUDENT": "MUKESH",
        "FATHER": "AMAR PRASAD",
        "Class": "06",
        "HINDI": 43,
        "ENGLISH": 36,
        "MATHS": 31,
        "SCINCE": 25,
        "Sst": 40,
        "COMPUTER": 24,
        "DRAWING": 19,
        "GK": 40,
        "PHYSICALEDUCATION": 46,
        "TOTAL": 304,
        "PRECENTAGE": 67.55555555555556
       },
       {
        "id": "20220610",
        "RollNo": "10",
        "STUDENT": "MAHI",
        "FATHER": "RAJENDRA",
        "Class": "06",
        "HINDI": 48,
        "ENGLISH": "A",
        "MATHS": 40,
        "SCINCE": 26,
        "Sst": 41,
        "COMPUTER": 25,
        "DRAWING": 16,
        "GK": 42,
        "PHYSICALEDUCATION": 48,
        "TOTAL": 286,
        "PRECENTAGE": 63.55555555555556
       },
       {
        "id": "20220611",
        "RollNo": "11",
        "STUDENT": "NISHA",
        "FATHER": "OM PRAKASH",
        "Class": "06",
        "HINDI": 48,
        "ENGLISH": 17,
        "MATHS": 17,
        "SCINCE": 30,
        "Sst": 28,
        "COMPUTER": 22,
        "DRAWING": 10,
        "GK": 45,
        "PHYSICALEDUCATION": 47,
        "TOTAL": 264,
        "PRECENTAGE": 58.666666666666664
       },
       {
        "id": "20220612",
        "RollNo": "12",
        "STUDENT": "PRINCE",
        "FATHER": "GYANI RAM",
        "Class": "06",
        "HINDI": 48,
        "ENGLISH": 38,
        "MATHS": 39,
        "SCINCE": 27,
        "Sst": 32,
        "COMPUTER": 20,
        "DRAWING": 32,
        "GK": 38,
        "PHYSICALEDUCATION": 49,
        "TOTAL": 323,
        "PRECENTAGE": 71.77777777777777
       },
       {
        "id": "20220613",
        "RollNo": "13",
        "STUDENT": "PAYAL",
        "FATHER": "TATIYA RAM",
        "Class": "06",
        "HINDI": 23,
        "ENGLISH": 4,
        "MATHS": 0,
        "SCINCE": 24,
        "Sst": 32,
        "COMPUTER": 16,
        "DRAWING": 8,
        "GK": 44,
        "PHYSICALEDUCATION": 47,
        "TOTAL": 198,
        "PRECENTAGE": 44
       },
       {
        "id": "20220614",
        "RollNo": "14",
        "STUDENT": "ROSHINI",
        "FATHER": "BRIJ KISHOR",
        "Class": "06",
        "HINDI": 48,
        "ENGLISH": 45,
        "MATHS": 30,
        "SCINCE": 36,
        "Sst": 33,
        "COMPUTER": 18,
        "DRAWING": 22,
        "GK": 46,
        "PHYSICALEDUCATION": 48,
        "TOTAL": 326,
        "PRECENTAGE": 72.44444444444444
       },
       {
        "id": "20220615",
        "RollNo": "15",
        "STUDENT": "RONAK",
        "FATHER": "GIRRAJ SINGH",
        "Class": "06",
        "HINDI": 40,
        "ENGLISH": 31,
        "MATHS": 43,
        "SCINCE": 32,
        "Sst": 39,
        "COMPUTER": 13,
        "DRAWING": 31,
        "GK": 38,
        "PHYSICALEDUCATION": 48,
        "TOTAL": 315,
        "PRECENTAGE": 70
       },
       {
        "id": "20220616",
        "RollNo": "16",
        "STUDENT": "SHIVA",
        "FATHER": "RAJENDRA",
        "Class": "06",
        "HINDI": 46,
        "ENGLISH": 31,
        "MATHS": 25,
        "SCINCE": 20,
        "Sst": 31,
        "COMPUTER": 14,
        "DRAWING": 24,
        "GK": 42,
        "PHYSICALEDUCATION": 48,
        "TOTAL": 281,
        "PRECENTAGE": 62.44444444444445
       },
       {
        "id": "20220617",
        "RollNo": "17",
        "STUDENT": "SUDHA",
        "FATHER": "MAN SINGH",
        "Class": "06",
        "HINDI": 42,
        "ENGLISH": 29,
        "MATHS": 34,
        "SCINCE": 24,
        "Sst": 27,
        "COMPUTER": 10,
        "DRAWING": 16,
        "GK": 45,
        "PHYSICALEDUCATION": 47,
        "TOTAL": 274,
        "PRECENTAGE": 60.88888888888889
       },
       {
        "id": "20220618",
        "RollNo": "18",
        "STUDENT": "SANJANA",
        "FATHER": "MUKESH",
        "Class": "06",
        "HINDI": 0,
        "ENGLISH": 19,
        "MATHS": 3,
        "SCINCE": 20,
        "Sst": 22,
        "COMPUTER": "A",
        "DRAWING": 25,
        "GK": 44,
        "PHYSICALEDUCATION": 48,
        "TOTAL": 181,
        "PRECENTAGE": 40.22222222222222
       },
       {
        "id": "20220619",
        "RollNo": "19",
        "STUDENT": "TULISHI",
        "FATHER": "RAM DATT",
        "Class": "06",
        "HINDI": 23,
        "ENGLISH": 2,
        "MATHS": 30,
        "SCINCE": 28,
        "Sst": 19,
        "COMPUTER": "A",
        "DRAWING": "A",
        "GK": 42,
        "PHYSICALEDUCATION": 47,
        "TOTAL": 191,
        "PRECENTAGE": 42.44444444444444
       },
       {
        "id": "20220620",
        "RollNo": "20",
        "STUDENT": "VISHAL",
        "FATHER": "VEERI SINGH",
        "Class": "06",
        "HINDI": 24,
        "ENGLISH": 10,
        "MATHS": 25,
        "SCINCE": 23,
        "Sst": 27,
        "COMPUTER": 24,
        "DRAWING": 13,
        "GK": 36,
        "PHYSICALEDUCATION": 46,
        "TOTAL": 228,
        "PRECENTAGE": 50.66666666666667
       },
       {
        "id": "20220621",
        "RollNo": "21",
        "STUDENT": "KHUSHI",
        "FATHER": "KAMAL SINGH",
        "Class": "06",
        "HINDI": 45,
        "ENGLISH": 31,
        "MATHS": 32,
        "SCINCE": 26,
        "Sst": 22,
        "COMPUTER": 28,
        "DRAWING": 19,
        "GK": 45,
        "PHYSICALEDUCATION": 48,
        "TOTAL": 296,
        "PRECENTAGE": 65.77777777777779
       },
       {
        "id": "20220622",
        "RollNo": "22",
        "STUDENT": "ABHAY",
        "FATHER": "SANTOSH",
        "Class": "06",
        "HINDI": 6,
        "ENGLISH": 5,
        "MATHS": 22,
        "SCINCE": 6,
        "Sst": 19,
        "COMPUTER": 14,
        "DRAWING": 13,
        "GK": 30,
        "PHYSICALEDUCATION": 49,
        "TOTAL": 164,
        "PRECENTAGE": 36.44444444444444
       },
       {
        "id": "20220623",
        "RollNo": "23",
        "STUDENT": "RONAK",
        "FATHER": " ",
        "Class": "06",
        "HINDI": 48,
        "ENGLISH": 25,
        "MATHS": 24,
        "SCINCE": 36,
        "Sst": 37,
        "COMPUTER": 21,
        "DRAWING": 23,
        "GK": 43,
        "PHYSICALEDUCATION": 49,
        "TOTAL": 306,
        "PRECENTAGE": 68
       },
       {
        "id": "20220624",
        "RollNo": "24",
        "STUDENT": "SACHIN",
        "FATHER": "SHIV KUMAR",
        "Class": "06",
        "HINDI": 32,
        "ENGLISH": "A",
        "MATHS": 30,
        "SCINCE": 6,
        "Sst": 24,
        "COMPUTER": 18,
        "DRAWING": 22,
        "GK": 37,
        "PHYSICALEDUCATION": 48,
        "TOTAL": 217,
        "PRECENTAGE": 48.22222222222222
       },
       {
        "id": "20220625",
        "RollNo": "25",
        "STUDENT": "SHIVAM",
        "FATHER": "PAPPU SINGH",
        "Class": "06",
        "HINDI": 35,
        "ENGLISH": 25,
        "MATHS": 48,
        "SCINCE": 20,
        "Sst": 27,
        "COMPUTER": 24,
        "DRAWING": 30,
        "GK": 35,
        "PHYSICALEDUCATION": 48,
        "TOTAL": 292,
        "PRECENTAGE": 64.88888888888889
       }
      ]
  
      
       
        
         export default Marks;
        
    
    